Repository acts-project/traccc, pull requests merged in 2021-09, with the labels that each got.

#83 Set c++17 cuda standard
  CMakeLists.txt
Labels: build

#82 use `unsigned int` instead of `size_t` for seed finding
  core/include/edm/container.hpp
  core/include/edm/internal_spacepoint.hpp
  core/include/seeding/detail/singlet.hpp
  core/include/seeding/doublet_finding.hpp
  core/include/seeding/seed_finding.hpp
  device/cuda/src/seeding/doublet_finding.cu
  device/cuda/src/seeding/seed_selecting.cu
  device/cuda/src/seeding/triplet_counting.cu
  device/cuda/src/seeding/triplet_finding.cu
  device/cuda/src/seeding/weight_updating.cu
Labels: refactor

#78 CI build for CUDA
  .github/workflows/builds.yml
Labels: cicd

#88 [bug] fix install path
  io/CMakeLists.txt
Labels: bug

#89 Add detray dependency
  CMakeLists.txt
  cmake/traccc-dependencies.cmake
  cmake/traccc-detray.cmake
  extern/CMakeLists.txt
Labels: build

#87 Implement improved algorithm semantics
  core/include/clusterization/component_connection.hpp
  core/include/clusterization/measurement_creation.hpp
  core/include/clusterization/spacepoint_formation.hpp
  core/include/seeding/doublet_finding.hpp
  core/include/seeding/seed_filtering.hpp
  core/include/seeding/seed_finding.hpp
  core/include/seeding/triplet_finding.hpp
  core/include/utils/algorithm.hpp
  examples/algorithms/cpu/include/clusterization/clusterization_algorithm.hpp
  examples/algorithms/cpu/include/track_finding/seeding_algorithm.hpp
  examples/run/cpu/ccl_example.cpp
  examples/run/cpu/seq_example.cpp
  examples/run/cpu/seq_single_module.cpp
  examples/run/cuda/seq_example_cuda.cpp
  examples/run/openmp/io_decoupled/io_dec_par_example.cpp
  examples/run/openmp/par_example.cpp
  tests/CMakeLists.txt
  tests/core/CMakeLists.txt
  tests/core/algorithm_tests.cpp
  tests/cpu/algorithms/component_connection_tests.cpp
Labels: refactor

#90 Improve the numerical stability of measurement variance calculation
  core/include/clusterization/measurement_creation.hpp
Labels: bug
