Repository acts-project/traccc, pull requests merged in 2021-08, with the labels that each got.

#35 Port ACTS binning algorithm for CPU
  CMakeLists.txt
  core/CMakeLists.txt
  core/include/edm/internal_spacepoint.hpp
  core/include/seeding/detail/bin_finder.hpp
  core/include/seeding/detail/doublet.hpp
  core/include/seeding/detail/lin_circle.hpp
  core/include/seeding/detail/seeding_config.hpp
  core/include/seeding/detail/singlet.hpp
  core/include/seeding/detail/spacepoint_grid.hpp
  core/include/seeding/detail/statistics.hpp
  core/include/seeding/detail/triplet.hpp
  core/include/seeding/spacepoint_grouping.hpp
  examples/cpu/seq_example.cpp
Labels: enhancement

#62 Remove loud include of Acts package
  CMakeLists.txt
Labels: build

#63 Clean up unused variables in CSV module
  io/include/csv/csv_io.hpp
Labels: cleanup

#56 Implement a fast GPU-friendly map for module IDs
  core/include/geometry/module_map.hpp
  tests/cpu/CMakeLists.txt
  tests/cpu/geometry/CMakeLists.txt
  tests/cpu/geometry/module_map_tests.cpp
Labels: enhancement

#60 Decouple I/O from traccc's algorithm
  examples/openmp/CMakeLists.txt
  examples/openmp/io_decoupled/CMakeLists.txt
  examples/openmp/io_decoupled/io_dec_par_example.cpp
  io/include/reader.hpp
  io/include/tmp_edm.hpp
  io/include/writer.hpp
Labels: enhancement

#66 Various improvements to the new module map type
  core/include/geometry/module_map.hpp
  tests/cpu/geometry/module_map_tests.cpp
Labels: bug, enhancement, tests

#67 Move io related includes to `io` directory
  examples/cpu/ccl_example.cpp
  examples/cpu/seq_example.cpp
  examples/openmp/io_decoupled/io_dec_par_example.cpp
  examples/openmp/par_example.cpp
  io/include/io/csv.hpp
  io/include/io/demonstrator_edm.hpp
  io/include/io/reader.hpp
  io/include/io/writer.hpp
  tests/cpu/geometry/module_map_tests.cpp
  tests/cpu/io/csv_io_tests.cpp
Labels: refactor

#70 Centralize `geometry` typedef and use `geometry_map`
  core/include/geometry/geometry.hpp
  examples/cpu/seq_example.cpp
  examples/openmp/par_example.cpp
  io/include/io/csv.hpp
  io/include/io/demonstrator_edm.hpp
  io/include/io/reader.hpp
Labels: refactor

#69 Make a few methods `inline` that have to be
  io/include/io/csv.hpp
  io/include/io/reader.hpp
  io/include/io/writer.hpp
Labels: bug, build

#71 Run tests and examples in the CI
  .github/workflows/builds.yml
  examples/cpu/CMakeLists.txt
  examples/openmp/CMakeLists.txt
  examples/openmp/io_decoupled/CMakeLists.txt
Labels: cicd

#72 CMake Cleanup/Updates, main branch (2021.08.10.)
  CMakeLists.txt
  examples/CMakeLists.txt
  examples/cpu/CMakeLists.txt
  examples/openmp/CMakeLists.txt
  examples/openmp/io_decoupled/CMakeLists.txt
  tests/CMakeLists.txt
Labels: build

#68 Centralize per-event filename, data directory, clean up string usage
  examples/cpu/seq_example.cpp
  examples/openmp/par_example.cpp
  io/include/io/reader.hpp
  io/include/io/utils.hpp
  io/include/io/writer.hpp
  tests/cpu/geometry/module_map_tests.cpp
  tests/include/tests/data_test.hpp
Labels: refactor, cleanup

#81 Changing parameter pack container constructor into explicit parameter ones
  core/include/edm/container.hpp
  core/include/seeding/spacepoint_grouping.hpp
  device/cuda/include/cuda/seeding/seed_finding.hpp
Labels: bug
