Repository acts-project/traccc, pull requests merged in 2021-07, with the labels that each got.

#44 Introduce a pre-commit hook for clang-format
  .githooks/README.md
  .githooks/pre-commit
Labels: enhancement

#43 chore: Clang format sync with vecmem config
  .clang-format
  core/include/algorithms/component_connection.hpp
  core/include/algorithms/detail/sparse_ccl.hpp
  core/include/algorithms/measurement_creation.hpp
  core/include/algorithms/spacepoint_formation.hpp
  core/include/definitions/algebra.hpp
  core/include/edm/cell.hpp
  core/include/edm/cluster.hpp
  core/include/edm/container.hpp
  core/include/geometry/pixel_segmentation.hpp
  examples/cpu/seq_example.cpp
  examples/cpu/seq_single_module.cpp
  io/include/csv/csv_io.hpp
  tests/cpu/algorithms/component_connection_tests.cpp
  tests/cpu/io/csv_io_tests.cpp
Labels: formatting

#51 Use HTTPS for data submodule instead of SSH
  .gitmodules
Labels: bug

#50 Add a simple CI build workflow
  .github/workflows/builds.yml
Labels: cicd, enhancement

#36 Implement a common set of algorithm semantics
  core/include/algorithms/algorithm.hpp
  core/include/algorithms/component_connection.hpp
  core/include/algorithms/measurement_creation.hpp
  core/include/algorithms/spacepoint_formation.hpp
  examples/cpu/ccl_example.cpp
  examples/cpu/seq_example.cpp
  examples/cpu/seq_single_module.cpp
  tests/cpu/algorithms/component_connection_tests.cpp
Labels: enhancement

#53 Add macros for host and device qualifiers
  core/include/definitions/qualifiers.hpp
Labels: enhancement

#40 CPU parallel example
  examples/CMakeLists.txt
  examples/cpu/CMakeLists.txt
  examples/openmp/CMakeLists.txt
  examples/openmp/par_example.cpp
Labels: enhancement

#58 fix the check format and apply again
  .github/check_format.sh
  examples/openmp/par_example.cpp
Labels: formatting

#54 Add Python-based CCL data generator tool
  extras/README.md
  extras/ccl_generator/README.md
  extras/ccl_generator/ccl_generator.py
Labels: enhancement

#57 Add a fixture base class for tests using data
  tests/CMakeLists.txt
  tests/cpu/CMakeLists.txt
  tests/cpu/io/csv_io_tests.cpp
  tests/include/tests/data_test.hpp
Labels: refactor, tests

#55 Add Acts as a dependency through FetchContent
  CMakeLists.txt
  cmake/traccc-acts.cmake
  cmake/traccc-dependencies.cmake
  cmake/traccc-vecmem.cmake
Labels: build

#61 update acts version to 10.0.0
  cmake/traccc-acts.cmake
Labels: build

#59 Reorganizing the algorithm directory
  core/include/clusterization/component_connection.hpp
  core/include/clusterization/detail/sparse_ccl.hpp
  core/include/clusterization/measurement_creation.hpp
  core/include/clusterization/spacepoint_formation.hpp
  core/include/utils/algorithm.hpp
  examples/cpu/ccl_example.cpp
  examples/cpu/seq_example.cpp
  examples/cpu/seq_single_module.cpp
  examples/openmp/par_example.cpp
  tests/cpu/algorithms/component_connection_tests.cpp
Labels: refactor
