Repository acts-project/traccc, pull requests merged in 2022-03, with the labels that each got.

#140 SYCL HIP Backend Compatibility, main branch (2022.03.01.)
  device/sycl/CMakeLists.txt
  examples/run/sycl/CMakeLists.txt
Labels: enhancement

#133 Add a mapper for validation purpose
  core/include/traccc/edm/cell.hpp
  core/include/traccc/edm/measurement.hpp
  core/include/traccc/edm/particle.hpp
  core/include/traccc/edm/spacepoint.hpp
  io/CMakeLists.txt
  io/include/traccc/io/csv.hpp
  io/include/traccc/io/mapper.hpp
  io/include/traccc/io/reader.hpp
  tests/io/CMakeLists.txt
  tests/io/mock_data/event000000000-cells.csv
  tests/io/mock_data/event000000000-hits.csv
  tests/io/mock_data/event000000000-particles_initial.csv
  tests/io/test_mapper.cpp
Labels: enhancement

#148 Remove dependency on ACTS unit test headers
  tests/common/tests/atlas_cuts.hpp
  tests/common/tests/space_point.hpp
  tests/cpu/compare_with_acts_seeding.cpp
Labels: bug, tests

#149 Fix range-loop-construct warning in module map
  core/include/traccc/geometry/module_map.hpp
Labels: bug

#151 Update algebra plugins to v0.8.0
  extern/algebra-plugins/CMakeLists.txt
Labels: build

#150 Run tests only for CPU-based builds
  .github/workflows/builds.yml
Labels: cicd

#153 Add infrastructure for CUDA testing
  tests/CMakeLists.txt
  tests/cuda/CMakeLists.txt
  tests/cuda/cuda_main.cpp
  tests/cuda/test_basic.cu
Labels: build, tests, cuda

#152 Migrate README flowchart to Mermaid
  README.md
  doc/images/algorithms.dot
  doc/images/algorithms.svg
Labels: documentation

#155 Update min version for CMake to build project
  cmake/traccc-compiler-options-cuda.cmake
Labels: bug, build

#159 Update SYCL Seedfinding Status, main branch (2022.03.31.)
  README.md
Labels: documentation
