Repository acts-project/traccc, pull requests merged in 2022-10, with the labels that each got.

#234 Changed configuration parameters' units to match ACTS
  core/include/traccc/seeding/detail/seeding_config.hpp
  core/src/seeding/seed_finding.cpp
  core/src/seeding/seeding_algorithm.cpp
  core/src/seeding/spacepoint_binning.cpp
  device/cuda/include/traccc/cuda/seeding/seed_finding.hpp
  device/cuda/src/seeding/seed_finding.cu
  device/cuda/src/seeding/seeding_algorithm.cpp
  device/cuda/src/seeding/spacepoint_binning.cu
  device/sycl/include/traccc/sycl/seeding/seed_finding.hpp
  device/sycl/src/seeding/seed_finding.sycl
  device/sycl/src/seeding/seeding_algorithm.cpp
  device/sycl/src/seeding/spacepoint_binning.sycl
  tests/cpu/compare_with_acts_seeding.cpp
Labels: refactor

#246 Refactor: Changed triplet counter class to include item_idx
  device/common/include/traccc/edm/device/triplet_counter.hpp
  device/common/include/traccc/seeding/device/find_triplets.hpp
  device/common/include/traccc/seeding/device/impl/count_triplets.ipp
  device/common/include/traccc/seeding/device/impl/find_triplets.ipp
  device/cuda/src/clusterization/clusterization_algorithm.cu
  device/cuda/src/seeding/seed_finding.cu
  device/sycl/src/seeding/seed_finding.sycl
Labels: refactor, improvement

#247 VecMem Update, Code Simplification, main branch (2022.10.10.)
  device/common/include/traccc/device/container_d2h_copy_alg.hpp
  device/common/include/traccc/device/impl/container_d2h_copy_alg.ipp
  device/common/include/traccc/device/impl/container_h2d_copy_alg.ipp
  device/cuda/include/traccc/cuda/seeding/seed_finding.hpp
  device/cuda/include/traccc/cuda/seeding/seeding_algorithm.hpp
  device/cuda/include/traccc/cuda/seeding/spacepoint_binning.hpp
  device/cuda/include/traccc/cuda/seeding/track_params_estimation.hpp
  device/cuda/src/seeding/seed_finding.cu
  device/cuda/src/seeding/seeding_algorithm.cpp
  device/cuda/src/seeding/spacepoint_binning.cu
  device/cuda/src/seeding/track_params_estimation.cu
  device/sycl/include/traccc/sycl/seeding/seed_finding.hpp
  device/sycl/include/traccc/sycl/seeding/seeding_algorithm.hpp
  device/sycl/include/traccc/sycl/seeding/spacepoint_binning.hpp
  device/sycl/include/traccc/sycl/seeding/track_params_estimation.hpp
  device/sycl/src/seeding/seed_finding.sycl
  device/sycl/src/seeding/seeding_algorithm.cpp
  device/sycl/src/seeding/spacepoint_binning.sycl
  device/sycl/src/seeding/track_params_estimation.sycl
  extern/vecmem/CMakeLists.txt
Labels: cleanup, cuda, sycl

#248 Seed EDM Update, main branch (2022.10.10.)
  core/include/traccc/edm/seed.hpp
  core/include/traccc/seeding/seed_filtering.hpp
  core/include/traccc/seeding/seed_finding.hpp
  core/include/traccc/seeding/seeding_algorithm.hpp
  core/include/traccc/seeding/track_params_estimation.hpp
  core/src/seeding/seed_filtering.cpp
  core/src/seeding/track_params_estimation.cpp
  device/common/include/traccc/seeding/device/impl/select_seeds.ipp
  device/common/include/traccc/seeding/device/select_seeds.hpp
  device/cuda/include/traccc/cuda/seeding/seed_finding.hpp
  device/cuda/include/traccc/cuda/seeding/seeding_algorithm.hpp
  device/cuda/include/traccc/cuda/seeding/track_params_estimation.hpp
  device/cuda/src/seeding/seed_finding.cu
  device/cuda/src/seeding/seeding_algorithm.cpp
  device/cuda/src/seeding/track_params_estimation.cu
  device/sycl/include/traccc/sycl/seeding/seed_finding.hpp
  device/sycl/include/traccc/sycl/seeding/seeding_algorithm.hpp
  device/sycl/include/traccc/sycl/seeding/track_params_estimation.hpp
  device/sycl/src/seeding/seed_finding.sycl
  device/sycl/src/seeding/seeding_algorithm.cpp
  device/sycl/src/seeding/track_params_estimation.sycl
  examples/performance/include/traccc/efficiency/seeding_performance_writer.hpp
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/seq_example_cuda.cpp
  examples/run/sycl/seeding_example_sycl.sycl
  examples/run/sycl/seq_example_sycl.sycl
Labels: cuda, sycl

#257 VecMem Upgrade, main branch (2022.10.25.)
  extern/vecmem/CMakeLists.txt
Labels: build

#254 Update detray version (v0.11.0 -> v0.12.0) and replace track parameter classes
  core/include/traccc/definitions/primitives.hpp
  core/include/traccc/definitions/track_parametrization.hpp
  core/include/traccc/edm/internal_spacepoint.hpp
  core/include/traccc/edm/track_parameters.hpp
  core/include/traccc/seeding/spacepoint_binning_helper.hpp
  core/include/traccc/seeding/track_params_estimation_helper.hpp
  core/src/seeding/track_params_estimation.cpp
  device/common/include/traccc/seeding/device/impl/count_grid_capacities.ipp
  device/common/include/traccc/seeding/device/impl/estimate_track_params.ipp
  device/common/include/traccc/seeding/device/impl/populate_grid.ipp
  extern/detray/CMakeLists.txt
  tests/cpu/compare_with_acts_seeding.cpp
Labels: refactor

#258 Improved count/find doublets performance
  core/include/traccc/seeding/doublet_finding_helper.hpp
  device/common/include/traccc/seeding/device/impl/find_doublets.ipp
Labels: improvement

#260 Moved device syncronisation statements to as late as possible
  device/cuda/src/clusterization/clusterization_algorithm.cu
  device/cuda/src/seeding/seed_finding.cu
  device/sycl/src/clusterization/clusterization_algorithm.sycl
  device/sycl/src/seeding/seed_finding.sycl
Labels: cuda, improvement, sycl

#259 Container Comparison Update, main branch (2022.10.26.)
  CMakeLists.txt
  device/common/include/traccc/seeding/device/impl/estimate_track_params.ipp
  examples/CMakeLists.txt
  examples/performance/CMakeLists.txt
  examples/run/cuda/CMakeLists.txt
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/seq_example_cuda.cpp
  examples/run/sycl/CMakeLists.txt
  examples/run/sycl/seeding_example_sycl.sycl
  examples/run/sycl/seq_example_sycl.sycl
  performance/CMakeLists.txt
  performance/include/traccc/efficiency/duplication_plot_tool.hpp
  performance/include/traccc/efficiency/eff_plot_tool.hpp
  performance/include/traccc/efficiency/helpers.hpp
  performance/include/traccc/efficiency/seeding_performance_writer.hpp
  performance/include/traccc/efficiency/track_classification.hpp
  performance/include/traccc/event/event_map.hpp
  performance/include/traccc/performance/collection_comparator.hpp
  performance/include/traccc/performance/container_comparator.hpp
  performance/include/traccc/performance/details/comparator_factory.hpp
  performance/include/traccc/performance/details/is_same_angle.hpp
  performance/include/traccc/performance/details/is_same_object.hpp
  performance/include/traccc/performance/details/is_same_scalar.hpp
  performance/include/traccc/performance/impl/collection_comparator.ipp
  performance/include/traccc/performance/impl/comparator_factory.ipp
  performance/include/traccc/performance/impl/container_comparator.ipp
  performance/include/traccc/performance/impl/is_same_measurement.ipp
  performance/include/traccc/performance/impl/is_same_object.ipp
  performance/include/traccc/performance/impl/is_same_seed.ipp
  performance/include/traccc/performance/impl/is_same_spacepoint.ipp
  performance/include/traccc/performance/impl/is_same_track_parameters.ipp
  performance/include/traccc/performance/impl/seed_comparator_factory.ipp
  performance/src/performance/details/comparator_factory.cpp
  performance/src/performance/details/is_same_angle.cpp
  performance/src/performance/details/is_same_object.cpp
  performance/src/performance/details/is_same_scalar.cpp
Labels: refactor, cuda, improvement, sycl
