Repository acts-project/traccc, pull requests merged in 2023-04, with the labels that each got.

#379 Minor fixes
  core/src/seeding/seed_finding.cpp
  io/src/csv/read_measurements.cpp
  io/src/csv/read_spacepoints_alt.cpp
Labels: bug

#378 Update vecmem and detray versions
  core/include/traccc/edm/track_state.hpp
  device/cuda/src/fitting/fitting_algorithm.cu
  device/cuda/src/seeding/seed_finding.cu
  device/cuda/src/seeding/spacepoint_binning.cu
  device/kokkos/src/seeding/spacepoint_binning.cpp
  device/sycl/src/fitting/fitting_algorithm.sycl
  device/sycl/src/seeding/seed_finding.sycl
  device/sycl/src/seeding/spacepoint_binning.sycl
  extern/detray/CMakeLists.txt
  extern/vecmem/CMakeLists.txt
  performance/include/traccc/resolution/fitting_performance_writer.hpp
  plugins/algebra/array/CMakeLists.txt
  plugins/algebra/array/include/traccc/plugins/algebra/array_definitions.hpp
  plugins/algebra/eigen/CMakeLists.txt
  plugins/algebra/smatrix/CMakeLists.txt
  plugins/algebra/vc/CMakeLists.txt
Labels: build, improvement

#376 Update README.md
  README.md
Labels: documentation, improvement

#369 Add quality reporting for seeds of arbitrary length
  core/include/traccc/edm/nseed.hpp
  examples/run/cuda/seeding_example_cuda.cpp
  performance/CMakeLists.txt
  performance/include/traccc/efficiency/nseed_performance_writer.hpp
  performance/include/traccc/efficiency/track_filter.hpp
  performance/include/traccc/efficiency/track_matcher.hpp
  performance/src/efficiency/nseed_performance_writer.cpp
  performance/src/efficiency/track_filter.cpp
  performance/src/efficiency/track_matcher.cpp
Labels: feature

#385 Add default destructors to virtual classes
  performance/include/traccc/efficiency/track_filter.hpp
  performance/include/traccc/efficiency/track_matcher.hpp
Labels: bug

#348 Implement near-transparent layout-swappable arrays
  core/include/traccc/utils/array_wrapper.hpp
  core/include/traccc/utils/functor.hpp
  tests/cuda/CMakeLists.txt
  tests/cuda/test_array_wrapper.cu
Labels: feature

#387 Reduce the memory usage of array wrapper tests
  tests/cuda/test_array_wrapper.cu
Labels: bug, tests

#237 ci: Add basic GPU CI
  .gitlab-ci.yml
Labels: cicd

#389 Remove git-lfs from actions. Update to checkout@v3
  .github/workflows/builds.yml
  .github/workflows/checks.yml
Labels: cicd

#377 Change CCL kernel to common code
  device/common/include/traccc/clusterization/device/ccl_kernel.hpp
  device/common/include/traccc/clusterization/device/impl/aggregate_cluster.ipp
  device/common/include/traccc/clusterization/device/impl/ccl_kernel.ipp
  device/cuda/CMakeLists.txt
  device/cuda/include/traccc/cuda/utils/barrier.hpp
  device/cuda/src/clusterization/clusterization_algorithm.cu
  device/sycl/CMakeLists.txt
  device/sycl/include/traccc/sycl/utils/barrier.hpp
  device/sycl/src/clusterization/clusterization_algorithm.sycl
  extern/vecmem/CMakeLists.txt
Labels: cuda, improvement, sycl

#380 Ensure synchronisation with async copies
  device/common/src/make_prefix_sum_buffer.cpp
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/seq_example_cuda.cpp
  examples/run/sycl/seeding_example_sycl.sycl
  examples/run/sycl/seq_example_sycl.sycl
Labels: bug, cuda, sycl

#344 Throughput Measurement Scripting, main branch (2023.03.11.)
  extras/traccc_throughput_mt_plotter.py
  extras/traccc_throughput_mt_profiler.sh
Labels: feature, performance

#391 Cleanup: Rename alt types.
  core/include/traccc/edm/seed.hpp
  core/include/traccc/edm/spacepoint.hpp
  examples/io/create_binaries.cpp
  examples/run/common/throughput_mt.hpp
  examples/run/common/throughput_mt.ipp
  examples/run/common/throughput_st.hpp
  examples/run/common/throughput_st.ipp
  examples/run/cpu/seeding_example.cpp
  examples/run/cpu/throughput_mt.cpp
  examples/run/cpu/throughput_st.cpp
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/seq_example_cuda.cpp
  examples/run/cuda/throughput_mt.cpp
  examples/run/cuda/throughput_st.cpp
  examples/run/kokkos/seeding_example_kokkos.cpp
  examples/run/openmp/io_dec_par_example.cpp
  examples/run/sycl/seeding_example_sycl.sycl
  examples/run/sycl/seq_example_sycl.sycl
  examples/run/sycl/throughput_mt.cpp
  examples/run/sycl/throughput_st.cpp
  io/CMakeLists.txt
  io/include/traccc/io/demonstrator_edm.hpp
  io/include/traccc/io/read.hpp
  io/include/traccc/io/read_spacepoints.hpp
  io/include/traccc/io/read_spacepoints_alt.hpp
  io/src/csv/read_spacepoints.cpp
  io/src/csv/read_spacepoints.hpp
  io/src/csv/read_spacepoints_alt.cpp
  io/src/csv/read_spacepoints_alt.hpp
  io/src/mapper.cpp
  io/src/read.cpp
  io/src/read_spacepoints.cpp
  io/src/read_spacepoints_alt.cpp
  tests/cpu/compare_with_acts_seeding.cpp
  tests/cpu/test_clusterization_resolution.cpp
  tests/io/test_binary.cpp
  tests/io/test_csv.cpp
Labels: cleanup
