Repository acts-project/traccc, pull requests merged in 2023-05, with the labels that each got.

#392 Remove synchronization from cuda chain
  device/cuda/include/traccc/cuda/clusterization/clusterization_algorithm.hpp
  device/cuda/include/traccc/cuda/seeding/seed_finding.hpp
  device/cuda/include/traccc/cuda/seeding/seeding_algorithm.hpp
  device/cuda/include/traccc/cuda/seeding/spacepoint_binning.hpp
  device/cuda/include/traccc/cuda/seeding/track_params_estimation.hpp
  device/cuda/include/traccc/cuda/utils/make_prefix_sum_buff.hpp
  device/cuda/src/clusterization/clusterization_algorithm.cu
  device/cuda/src/seeding/seed_finding.cu
  device/cuda/src/seeding/spacepoint_binning.cu
  device/cuda/src/seeding/track_params_estimation.cu
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/seq_example_cuda.cpp
  examples/run/sycl/seq_example_sycl.sycl
Labels: cuda, improvement

#393 Fix: use correct memory resources for host vectors
  device/cuda/src/clusterization/clusterization_algorithm.cu
  device/cuda/src/seeding/seed_finding.cu
  device/sycl/src/clusterization/clusterization_algorithm.sycl
  device/sycl/src/seeding/seed_finding.sycl
  examples/io/create_binaries.cpp
  examples/run/common/throughput_mt.ipp
  examples/run/common/throughput_st.ipp
  examples/run/cpu/ccl_example.cpp
  examples/run/cpu/seeding_example.cpp
  examples/run/cpu/seq_example.cpp
  examples/run/cuda/full_chain_algorithm.cpp
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/seq_example_cuda.cpp
  examples/run/kokkos/seeding_example_kokkos.cpp
  examples/run/openmp/par_example.cpp
  examples/run/sycl/full_chain_algorithm.sycl
  examples/run/sycl/seeding_example_sycl.sycl
  examples/run/sycl/seq_example_sycl.sycl
  examples/run/sycl/throughput_mt.cpp
  io/include/traccc/io/read.hpp
  io/include/traccc/io/read_cells.hpp
  io/include/traccc/io/read_measurements.hpp
  io/include/traccc/io/read_spacepoints.hpp
  io/include/traccc/io/reader_edm.hpp
  io/src/csv/read_cells.cpp
  io/src/csv/read_cells.hpp
  io/src/csv/read_measurements.cpp
  io/src/csv/read_measurements.hpp
  io/src/csv/read_spacepoints.cpp
  io/src/csv/read_spacepoints.hpp
  io/src/mapper.cpp
  io/src/read.cpp
  io/src/read_binary.hpp
  io/src/read_cells.cpp
  io/src/read_measurements.cpp
  io/src/read_spacepoints.cpp
  tests/common/tests/cca_test.hpp
  tests/cpu/compare_with_acts_seeding.cpp
  tests/cpu/test_clusterization_resolution.cpp
  tests/io/test_binary.cpp
  tests/io/test_csv.cpp
Labels: bug, performance

#363 Add ability to import CMake target for covfie
  CMakeLists.txt
  extern/covfie/CMakeLists.txt
  extern/detray/CMakeLists.txt
Labels: bug, build

#398 Update README.md
  README.md
Labels: documentation

#397 External packages only build when needed
  CMakeLists.txt
Labels: build, improvement

#402 Fix error in Spacepoint Binning
  device/kokkos/src/seeding/spacepoint_binning.cpp
Labels: bug, kokkos

#399 Clean up unit_vectors.hpp
  core/CMakeLists.txt
  core/include/traccc/edm/track_parameters.hpp
  core/include/traccc/utils/unit_vectors.hpp
  examples/options/CMakeLists.txt
  examples/options/include/traccc/options/particle_gen_options.hpp
  performance/CMakeLists.txt
  performance/include/traccc/efficiency/nseed_performance_writer.hpp
  performance/include/traccc/utils/ranges.hpp
  performance/src/efficiency/duplication_plot_tool.hpp
  performance/src/efficiency/eff_plot_tool.hpp
  performance/src/efficiency/track_filter.cpp
  tests/cpu/CMakeLists.txt
  tests/cpu/test_kalman_fitter.cpp
  tests/cpu/test_ranges.cpp
  tests/cuda/test_kalman_filter.cpp
  tests/sycl/test_kalman_filter.sycl
Labels: refactor, cleanup, shared

#400 Track candidate with `detray::barcode`
  core/include/traccc/edm/track_candidate.hpp
  io/include/traccc/io/event_map2.hpp
Labels: refactor

#395 Add tests for container copy
  tests/cpu/CMakeLists.txt
  tests/cpu/test_copy.cpp
  tests/cuda/CMakeLists.txt
  tests/cuda/test_copy.cu
  tests/cuda/test_thrust.cu
Labels: tests
