Repository acts-project/traccc, pull requests merged in 2023-09, with the labels that each got.

#453 Remove duplicate detector file option
  examples/options/src/options/full_tracking_input_options.cpp
Labels: bug

#454 is_same_object Warning Fix, main branch (2023.09.08.)
  performance/include/traccc/performance/impl/is_same_track_candidates.ipp
  performance/src/performance/details/is_same_object.cpp
Labels: bug, performance

#455 Compiler Option Fixes, main branch (2023.09.08.)
  cmake/traccc-compiler-options-cpp.cmake
  cmake/traccc-compiler-options-sycl.cmake
  core/CMakeLists.txt
  core/src/seeding/track_params_estimation.cpp
  examples/CMakeLists.txt
  extern/kokkos/CMakeLists.txt
  io/CMakeLists.txt
  performance/CMakeLists.txt
  performance/src/efficiency/nseed_performance_writer.cpp
  performance/src/performance/timer.cpp
  performance/src/performance/timing_info.cpp
Labels: bug, build, performance

#446 Track finding with measurement collection input
  core/include/traccc/edm/measurement.hpp
  core/include/traccc/finding/candidate_link.hpp
  core/include/traccc/finding/finding_algorithm.hpp
  core/include/traccc/finding/finding_algorithm.ipp
  device/common/CMakeLists.txt
  device/common/include/traccc/edm/device/finding_global_counter.hpp
  device/common/include/traccc/finding/device/build_tracks.hpp
  device/common/include/traccc/finding/device/count_measurements.hpp
  device/common/include/traccc/finding/device/count_threads.hpp
  device/common/include/traccc/finding/device/find_tracks.hpp
  device/common/include/traccc/finding/device/impl/build_tracks.ipp
  device/common/include/traccc/finding/device/impl/count_measurements.ipp
  device/common/include/traccc/finding/device/impl/count_threads.ipp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
  device/common/include/traccc/finding/device/impl/make_barcode_sequence.ipp
  device/common/include/traccc/finding/device/impl/make_module_map.ipp
  device/common/include/traccc/finding/device/impl/propagate_to_next_surface.ipp
  device/common/include/traccc/finding/device/make_barcode_sequence.hpp
  device/common/include/traccc/finding/device/make_module_map.hpp
  device/cuda/include/traccc/cuda/finding/finding_algorithm.hpp
  device/cuda/src/finding/finding_algorithm.cu
  examples/run/cpu/seeding_example.cpp
  examples/run/cpu/truth_finding_example.cpp
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/truth_finding_example_cuda.cpp
  io/include/traccc/io/read_measurements.hpp
  io/src/csv/read_measurements.hpp
  io/src/read_measurements.cpp
  tests/cpu/test_ckf_sparse_tracks.cpp
  tests/cuda/test_ckf_sparse_tracks.cpp
Labels: high prioirity

#456 Add measurement dimension and its subspace
  core/CMakeLists.txt
  core/include/traccc/edm/measurement.hpp
  core/include/traccc/edm/track_state.hpp
  core/include/traccc/fitting/kalman_filter/gain_matrix_smoother.hpp
  core/include/traccc/fitting/kalman_filter/gain_matrix_updater.hpp
  core/include/traccc/utils/subspace.hpp
Labels: high prioirity

#463 (Xcode) Warning Fix, main branch, 2023.09.30.
  performance/src/resolution/stat_plot_tool.cpp
Labels: improvement

#464 (Device) Clusterization Fix, main branch (2023.09.30.)
  core/include/traccc/clusterization/detail/measurement_creation_helper.hpp
  device/common/include/traccc/clusterization/device/impl/aggregate_cluster.ipp
Labels: bug, cuda, sycl, cpu
