Repository acts-project/traccc, pull requests merged in 2024-09, with the labels that each got.

#693 Add benchmark formatting to CI
  .github/check_format.sh
  benchmarks/cuda/toy_detector_cuda.cpp
Labels: cicd, formatting

#694 Fix integer comparison bugs in device CKF
  device/common/include/traccc/finding/device/impl/add_links_for_holes.ipp
  device/common/include/traccc/finding/device/impl/build_tracks.ipp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
Labels: bug, shared

#698 Remove artifact upload from format CI
  .github/workflows/checks.yml
Labels: bug, cicd

#705 Update version number to v0.16.0
  CMakeLists.txt
Labels: build

#704 Attach algebra-plugins define to core target
  CMakeLists.txt
  core/CMakeLists.txt
Labels: build

#695 Fuse inner loop kernels in device CKF
  core/include/traccc/finding/finding_config.hpp
  device/common/CMakeLists.txt
  device/common/include/traccc/edm/device/finding_global_counter.hpp
  device/common/include/traccc/finding/device/add_links_for_holes.hpp
  device/common/include/traccc/finding/device/count_measurements.hpp
  device/common/include/traccc/finding/device/find_tracks.hpp
  device/common/include/traccc/finding/device/impl/add_links_for_holes.ipp
  device/common/include/traccc/finding/device/impl/count_measurements.ipp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
  device/cuda/src/finding/finding_algorithm.cu
Labels: refactor, shared

#708 Clusterization Bugfix, main branch (2024.09.21.)
  device/common/include/traccc/clusterization/device/impl/ccl_kernel.ipp
Labels: bug

#707 VecMem 1.8.0 Update, main branch (2024.09.21.)
  extern/vecmem/CMakeLists.txt
Labels: build

#711 Silence Vc Warning(s), main branch (2024.09.21.)
  extern/algebra-plugins/CMakeLists.txt
Labels: build

#718 Update to VecMem 1.9.0, main branch (2024.09.30.)
  CMakeLists.txt
  extern/vecmem/CMakeLists.txt
Labels: build
