Repository acts-project/traccc, pull requests merged in 2024-05, with the labels that each got.

#561 Data V7, main branch (2024.05.03.)
  data/traccc_data_get_files.sh
  data/traccc_data_package_files.sh
Labels: build

#566 ODD ttbar Clusterization Fix, main branch (2024.05.04.)
  device/common/include/traccc/clusterization/device/ccl_kernel.hpp
Labels: cuda, improvement, sycl

#571 Kalman Fitter Step Aborter, main branch (2024.05.04.)
  core/CMakeLists.txt
  core/include/traccc/fitting/kalman_filter/kalman_fitter.hpp
  core/include/traccc/fitting/kalman_filter/kalman_step_aborter.hpp
Labels: cuda, improvement, cpu

#572 Tracking Throughput Measurements, main branch (2024.05.04.)
  examples/options/src/detector.cpp
  examples/run/common/throughput_mt.ipp
  examples/run/common/throughput_st.ipp
  examples/run/cpu/CMakeLists.txt
  examples/run/cpu/full_chain_algorithm.cpp
  examples/run/cpu/full_chain_algorithm.hpp
  examples/run/cuda/CMakeLists.txt
  examples/run/cuda/full_chain_algorithm.cpp
  examples/run/cuda/full_chain_algorithm.hpp
  examples/run/sycl/CMakeLists.txt
  examples/run/sycl/full_chain_algorithm.hpp
  examples/run/sycl/full_chain_algorithm.sycl
  io/include/traccc/io/read.hpp
  io/src/read.cpp
Labels: build, cuda, improvement, sycl, cpu, examples

#574 Spacepoint OBJ Writing, main branch (2024.05.05.)
  examples/options/include/traccc/options/output_data.hpp
  examples/options/src/output_data.cpp
  examples/run/cpu/seq_example.cpp
  io/CMakeLists.txt
  io/include/traccc/io/data_format.hpp
  io/include/traccc/io/utils.hpp
  io/src/data_format.cpp
  io/src/obj/write_spacepoints.cpp
  io/src/obj/write_spacepoints.hpp
  io/src/utils.cpp
  io/src/write.cpp
Labels: feature, cpu, examples

#576 CUDA Throughput Improvement, main branch (2024.05.06.)
  examples/run/cuda/full_chain_algorithm.cpp
  examples/run/cuda/full_chain_algorithm.hpp
  io/src/event_map2.cpp
  io/src/mapper.cpp
  io/src/read_cells.cpp
  io/src/read_digitization_config.cpp
  io/src/read_geometry.cpp
  io/src/read_measurements.cpp
  io/src/read_particles.cpp
  io/src/read_spacepoints.cpp
  performance/src/performance/details/is_same_object.cpp
  tests/io/test_mapper.cpp
Labels: cuda, examples

#577 README Update, main branch (2024.05.07.)
  README.md
Labels: documentation

#581 ODD Strip Module Handling, main branch (2024.05.08.)
  core/include/traccc/clusterization/impl/measurement_creation.ipp
  core/include/traccc/geometry/pixel_data.hpp
  device/common/include/traccc/clusterization/device/impl/aggregate_cluster.ipp
  io/include/traccc/io/digitization_config.hpp
  io/src/csv/read_cells.cpp
  io/src/read_digitization_config.cpp
Labels: cuda, improvement, sycl, cpu

#585 ROOT Build Fix, main branch (2024.05.13.)
  CMakePresets.json
Labels: bug, build

#591 oneAPI 2024.1.0 Support, main branch (2024.05.15.)
  core/CMakeLists.txt
  core/include/traccc/definitions/math.hpp
  core/include/traccc/edm/cell.hpp
  core/include/traccc/edm/measurement.hpp
  core/include/traccc/edm/spacepoint.hpp
  core/include/traccc/seeding/doublet_finding_helper.hpp
  core/include/traccc/seeding/spacepoint_binning_helper.hpp
  core/include/traccc/seeding/track_params_estimation_helper.hpp
  core/include/traccc/seeding/triplet_finding_helper.hpp
  device/common/include/traccc/finding/device/impl/apply_interaction.ipp
  device/common/include/traccc/seeding/device/impl/update_triplet_weights.ipp
Labels: improvement

#583 Data Ignore Update, main branch (2024.05.11.)
  data/.gitignore
Labels: improvement

#588 More (Wavefront) Obj Writing, main branch (2024.05.13.)
  examples/run/cpu/seq_example.cpp
  io/CMakeLists.txt
  io/include/traccc/io/write.hpp
  io/src/obj/write_seeds.cpp
  io/src/obj/write_seeds.hpp
  io/src/obj/write_track_candidates.cpp
  io/src/obj/write_track_candidates.hpp
  io/src/write.cpp
Labels: feature, cpu, examples

#597 Algebra Plugins Update, main branch (2024.05.30.)
  core/include/traccc/edm/track_state.hpp
  extern/algebra-plugins/CMakeLists.txt
Labels: build

#598 Add missing ACTS JSON dependency
  CMakeLists.txt
Labels: bug, build

#601 Remove use of deprecated `std::is_pod` type trait
  core/include/traccc/utils/array_wrapper.hpp
Labels: refactor

#603 GPU CI Updates, main branch (2024.05.31.)
  .github/ci_setup.sh
  .github/workflows/builds.yml
Labels: cicd
