Repository acts-project/traccc, pull requests merged in 2024-12, with the labels that each got.

#789 Acts 38.0.0 Update, main branch (2024.12.02.)
  extern/acts/CMakeLists.txt
Labels: build

#790 Thrust Usage Update, main branch (2024.12.02.)
  CMakeLists.txt
  cmake/traccc-config.cmake.in
  device/common/include/traccc/finding/device/find_tracks.hpp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
  device/cuda/CMakeLists.txt
  device/sycl/CMakeLists.txt
  tests/cuda/CMakeLists.txt
Labels: build, cuda, sycl

#791 Atomic Reference Fixes, main branch (2024.12.02.)
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
Labels: bug

#792 Externals Update, main branch (2024.12.03.)
  extern/CMakeLists.txt
  extern/acts/CMakeLists.txt
  extern/algebra-plugins/CMakeLists.txt
  extern/alpaka/CMakeLists.txt
  extern/benchmark/CMakeLists.txt
  extern/cccl/CMakeLists.txt
  extern/covfie/CMakeLists.txt
  extern/detray/CMakeLists.txt
  extern/dfelibs/CMakeLists.txt
  extern/dpl/CMakeLists.txt
  extern/eigen3/CMakeLists.txt
  extern/googletest/CMakeLists.txt
  extern/indicators/CMakeLists.txt
  extern/kokkos/CMakeLists.txt
  extern/rocThrust/CMakeLists.txt
  extern/tbb/CMakeLists.txt
  extern/vecmem/CMakeLists.txt
Labels: build

#793 oneAPI 2025 / SYCL2020 Compatibility, main branch (2024.12.03.)
  .github/ci_setup.sh
  .github/workflows/builds.yml
  core/include/traccc/definitions/math.hpp
  device/sycl/include/traccc/sycl/utils/calculate1DimNdRange.hpp
  device/sycl/include/traccc/sycl/utils/make_prefix_sum_buff.hpp
  device/sycl/src/fitting/fit_tracks.hpp
  device/sycl/src/sanity/contiguous_on.hpp
  device/sycl/src/sanity/ordered_on.hpp
  device/sycl/src/seeding/silicon_pixel_spacepoint_formation.hpp
  device/sycl/src/seeding/spacepoint_binning.sycl
  device/sycl/src/utils/barrier.hpp
  device/sycl/src/utils/get_queue.hpp
  examples/run/sycl/CMakeLists.txt
  examples/run/sycl/seeding_example_sycl.sycl
  examples/run/sycl/seq_example_sycl.sycl
  examples/run/sycl/sycl_language_example.sycl
  extern/acts/CMakeLists.txt
  tests/sycl/test_barrier.sycl
  tests/sycl/test_cca.sycl
  tests/sycl/test_dpl.sycl
  tests/sycl/test_kalman_fitter_telescope.sycl
  tests/sycl/test_mutex.sycl
  tests/sycl/test_sanity_contiguous_on.sycl
  tests/sycl/test_sanity_ordered_on.sycl
  tests/sycl/test_sort.sycl
  tests/sycl/test_unique_lock.sycl
Labels: cicd, build, sycl

#796 Use Switch Instead of If, main branch (2024.12.04.)
  core/include/traccc/edm/track_state.hpp
  core/include/traccc/fitting/kalman_filter/gain_matrix_updater.hpp
Labels: improvement

#799 SYCL Tweaks, main branch (2024.12.07.)
  device/alpaka/src/utils/barrier.hpp
  device/common/include/traccc/clusterization/device/ccl_kernel.hpp
  device/common/include/traccc/clusterization/device/impl/ccl_kernel.ipp
  device/common/include/traccc/device/sort.hpp
  device/cuda/src/utils/barrier.hpp
  device/sycl/CMakeLists.txt
  device/sycl/include/traccc/sycl/utils/thread_id.hpp
  device/sycl/src/clusterization/clusterization_algorithm.sycl
  device/sycl/src/fitting/fit_tracks.hpp
  device/sycl/src/sanity/contiguous_on.hpp
  device/sycl/src/sanity/ordered_on.hpp
  device/sycl/src/seeding/seed_finding.sycl
  device/sycl/src/seeding/silicon_pixel_spacepoint_formation.hpp
  device/sycl/src/seeding/spacepoint_binning.sycl
  device/sycl/src/seeding/track_params_estimation.sycl
  device/sycl/src/utils/barrier.hpp
  device/sycl/src/utils/calculate1DimNdRange.hpp
  device/sycl/src/utils/calculate1DimNdRange.sycl
  device/sycl/src/utils/thread_id.hpp
  tests/sycl/test_barrier.sycl
  tests/sycl/test_sanity_contiguous_on.sycl
  tests/sycl/test_sanity_ordered_on.sycl
  tests/sycl/test_sort.sycl
Labels: bug, cleanup, sycl

#798 ref: Update to detray version 0.85.0 and adapt to new algebra-plugins API
  core/include/traccc/definitions/primitives.hpp
  core/include/traccc/edm/track_state.hpp
  core/include/traccc/fitting/kalman_filter/gain_matrix_smoother.hpp
  core/include/traccc/fitting/kalman_filter/gain_matrix_updater.hpp
  core/include/traccc/seeding/detail/seeding_config.hpp
  core/include/traccc/seeding/spacepoint_binning_helper.hpp
  core/include/traccc/seeding/track_params_estimation_helper.hpp
  core/include/traccc/utils/seed_generator.hpp
  core/include/traccc/utils/subspace.hpp
  extern/algebra-plugins/CMakeLists.txt
  extern/detray/CMakeLists.txt
  io/src/csv/make_measurement_edm.cpp
  io/src/csv/read_measurements.cpp
  performance/include/traccc/efficiency/nseed_performance_writer.hpp
  performance/include/traccc/resolution/fitting_performance_writer.hpp
  performance/src/efficiency/duplication_plot_tool.hpp
  performance/src/efficiency/eff_plot_tool.hpp
  performance/src/efficiency/fake_tracks_plot_tool.hpp
  performance/src/efficiency/finding_performance_writer.cpp
  performance/src/efficiency/seeding_performance_writer.cpp
  performance/src/efficiency/track_filter.cpp
  performance/src/resolution/res_plot_tool.cpp
  plugins/algebra/CMakeLists.txt
  plugins/algebra/array/include/traccc/plugins/algebra/array_definitions.hpp
  plugins/algebra/eigen/include/traccc/plugins/algebra/eigen_definitions.hpp
  plugins/algebra/smatrix/include/traccc/plugins/algebra/smatrix_definitions.hpp
  plugins/algebra/vc_aos/CMakeLists.txt
  plugins/algebra/vc_aos/include/traccc/plugins/algebra/vc_aos_definitions.hpp
  plugins/algebra/vecmem/include/traccc/plugins/algebra/vecmem_definitions.hpp
  simulation/include/traccc/simulation/measurement_smearer.hpp
  tests/cpu/test_track_params_estimation.cpp
Labels: bug, refactor

#802 Spacepoint formation algorithm change
  device/cuda/src/seeding/spacepoint_formation_algorithm.cu
Labels: cuda
