Repository acts-project/traccc, pull requests merged in 2024-06, with the labels that each got.

#606 Project Version Update, main branch (2024.06.07.)
  CMakeLists.txt
Labels: build

#612 Bump vecmem version to 1.6.0
  extern/vecmem/CMakeLists.txt
Labels: build

#614 Fix broken CUDA unit test after #605
  tests/cuda/test_clusterization.cpp
Labels: bug, tests, cuda

#610 Add blockwise add and count in CUDA and SYCL
  device/cuda/src/utils/barrier.hpp
  device/sycl/CMakeLists.txt
  device/sycl/src/clusterization/clusterization_algorithm.sycl
  device/sycl/src/utils/barrier.hpp
  tests/cuda/CMakeLists.txt
  tests/cuda/test_barrier.cu
  tests/sycl/CMakeLists.txt
  tests/sycl/test_barrier.sycl
Labels: feature, cuda, sycl

#617 Bump detray version to v0.67.0
  examples/simulation/simulate.cpp
  examples/simulation/simulate_telescope.cpp
  examples/simulation/simulate_toy_detector.cpp
  examples/simulation/simulate_wire_chamber.cpp
  extern/detray/CMakeLists.txt
  tests/common/tests/kalman_fitting_test.hpp
  tests/cpu/test_simulation.cpp
Labels: build

#619 Fix bug in CUDA barrier unit test
  tests/cuda/test_barrier.cu
Labels: bug, tests, cuda

#618 Fix SYCL clustering test after #605
  tests/sycl/test_clusterization.sycl
Labels: bug, tests, sycl

#616 GitLab CI Update, main branch (2024.06.18.)
  .github/ci_plugin_install.sh
  .gitlab-ci.yml
  tests/cuda/test_cca.cpp
  tests/cuda/test_ckf_combinatorics_telescope.cpp
  tests/cuda/test_ckf_toy_detector.cpp
  tests/cuda/test_kalman_fitter_telescope.cpp
  tests/cuda/test_spacepoint_formation.cpp
  tests/cuda/test_thrust.cu
  tests/sycl/test_kalman_fitter_telescope.sycl
  tests/sycl/test_spacepoint_formation.sycl
Labels: cicd

#607 Add a simple spinlock mutex type
  device/common/include/traccc/device/impl/mutex.ipp
  device/common/include/traccc/device/impl/unique_lock.ipp
  device/common/include/traccc/device/mutex.hpp
  device/common/include/traccc/device/unique_lock.hpp
  tests/cuda/CMakeLists.txt
  tests/cuda/test_mutex.cu
  tests/cuda/test_unique_lock.cu
  tests/sycl/CMakeLists.txt
  tests/sycl/test_mutex.sycl
  tests/sycl/test_unique_lock.sycl
Labels: feature

#620 Fix search window syntax
  README.md
Labels: bug, documentation

#625 Update OneAPI CUDA and ROCm images
  .github/ci_plugin_install.sh
  .gitlab-ci.yml
Labels: bug, cicd

#599 Add new CI platform for C++20 builds
  .github/workflows/builds.yml
Labels: cicd, improvement

#630 Add SYCL tests for CCA code
  tests/sycl/CMakeLists.txt
  tests/sycl/test_cca.sycl
Labels: tests, sycl

#629 Improve numerical stability of CCA variance
  core/include/traccc/clusterization/impl/measurement_creation.ipp
  core/src/clusterization/measurement_creation_algorithm.cpp
  device/common/include/traccc/clusterization/device/impl/aggregate_cluster.ipp
  tests/common/tests/cca_test.hpp
Labels: tests, improvement, shared

#626 Add CLI options to configuration type conversion
  examples/options/include/traccc/options/clusterization.hpp
  examples/options/include/traccc/options/details/config_provider.hpp
  examples/options/include/traccc/options/track_finding.hpp
  examples/options/include/traccc/options/track_propagation.hpp
  examples/options/src/clusterization.cpp
  examples/options/src/track_finding.cpp
  examples/options/src/track_propagation.cpp
  examples/run/common/throughput_mt.ipp
  examples/run/common/throughput_st.ipp
  examples/run/cpu/seeding_example.cpp
  examples/run/cpu/seq_example.cpp
  examples/run/cpu/truth_finding_example.cpp
  examples/run/cpu/truth_fitting_example.cpp
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/seq_example_cuda.cpp
  examples/run/cuda/truth_finding_example_cuda.cpp
  examples/run/cuda/truth_fitting_example_cuda.cpp
  examples/run/sycl/seq_example_sycl.sycl
  examples/simulation/simulate.cpp
  examples/simulation/simulate_telescope.cpp
  examples/simulation/simulate_toy_detector.cpp
  examples/simulation/simulate_wire_chamber.cpp
Labels: refactor, examples

#634 Download data files after build in CI
  .github/workflows/builds.yml
Labels: cicd, improvement

#631 Add infrastructure for working with concepts
  .github/workflows/builds.yml
  CMakeLists.txt
  core/CMakeLists.txt
  core/include/traccc/definitions/concepts.hpp
Labels: feature, build
