Repository acts-project/traccc, pull requests merged in 2024-08, with the labels that each got.

#628 build: update extern tags
  cmake/traccc-config.cmake.in
  core/include/traccc/finding/finding_algorithm.ipp
  core/include/traccc/utils/seed_generator.hpp
  device/common/include/traccc/finding/device/count_measurements.hpp
  device/common/include/traccc/finding/device/find_tracks.hpp
  device/common/include/traccc/finding/device/impl/apply_interaction.ipp
  extern/detray/CMakeLists.txt
Labels: bug, build

#662 Update version tag to v0.13.0
  CMakeLists.txt
Labels: build

#664 Fix full chain algorithm deallocation order
  examples/run/alpaka/full_chain_algorithm.cpp
  examples/run/cuda/full_chain_algorithm.cpp
  examples/run/sycl/full_chain_algorithm.sycl
Labels: bug, cuda, sycl, alpaka, examples

#632 Implement block-wide odd-even sort
  device/common/include/traccc/device/sort.hpp
  tests/cuda/CMakeLists.txt
  tests/cuda/test_sort.cu
  tests/sycl/CMakeLists.txt
  tests/sycl/test_sort.sycl
Labels: feature, shared

#668 Use traccc scalar type in seeding config
  core/include/traccc/seeding/detail/seeding_config.hpp
Labels: bug

#663 Increase minimum CMake version to 3.22
  CMakeLists.txt
  device/cuda/CMakeLists.txt
Labels: bug, build

#673 Externals Update, main branch (2024.08.14.)
  extern/googletest/CMakeLists.txt
  extern/vecmem/CMakeLists.txt
  tests/common/tests/cca_test.hpp
Labels: build, tests, high prioirity

#677 macOS Fixes, main branch (2024.08.14.)
  core/include/traccc/clusterization/clustering_config.hpp
  extern/cccl/CMakeLists.txt
Labels: build, cpu

#678 Project Version Update, main branch (2024.08.15.)
  CMakeLists.txt
Labels: build, high prioirity

#680 Add event throughput in the benchmark
  benchmarks/cpu/toy_detector_cpu.cpp
  benchmarks/cuda/toy_detector_cuda.cpp
Labels: high prioirity

#672 Disable Default CUDA Build, main branch (2024.08.13.)
  CMakeLists.txt
Labels: build

#686 Simplify ODD Strip Module Handling, main branch (2024.08.20.)
  core/include/traccc/clusterization/impl/measurement_creation.ipp
  core/include/traccc/geometry/pixel_data.hpp
  device/common/include/traccc/clusterization/device/impl/aggregate_cluster.ipp
  io/include/traccc/io/digitization_config.hpp
  io/src/csv/read_cells.cpp
  io/src/read_digitization_config.cpp
Labels: improvement

#653 Enable tests for Alpaka builds
  .github/workflows/builds.yml
Labels: cicd, alpaka
