Repository acts-project/traccc, pull requests merged in 2025-01, with the labels that each got.

#808 Track Finding Cleanup, main branch (2025.01.07.)
  .gitlab-ci.yml
  device/common/include/traccc/device/global_index.hpp
  device/common/include/traccc/finding/device/apply_interaction.hpp
  device/common/include/traccc/finding/device/build_tracks.hpp
  device/common/include/traccc/finding/device/fill_sort_keys.hpp
  device/common/include/traccc/finding/device/find_tracks.hpp
  device/common/include/traccc/finding/device/impl/apply_interaction.ipp
  device/common/include/traccc/finding/device/impl/build_tracks.ipp
  device/common/include/traccc/finding/device/impl/fill_sort_keys.ipp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
  device/common/include/traccc/finding/device/impl/make_barcode_sequence.ipp
  device/common/include/traccc/finding/device/impl/propagate_to_next_surface.ipp
  device/common/include/traccc/finding/device/impl/prune_tracks.ipp
  device/common/include/traccc/finding/device/make_barcode_sequence.hpp
  device/common/include/traccc/finding/device/propagate_to_next_surface.hpp
  device/common/include/traccc/finding/device/prune_tracks.hpp
  device/cuda/src/finding/finding_algorithm.cu
  device/cuda/src/finding/kernels/specializations/find_tracks_src.cuh
  device/cuda/src/finding/kernels/specializations/propagate_to_next_surface_src.cuh
Labels: cuda, improvement, shared

#809 Simulation Tweaks, main branch (2025.01.08.)
  simulation/include/traccc/simulation/measurement_smearer.hpp
  simulation/include/traccc/simulation/smearing_writer.hpp
Labels: cleanup

#811 SYCL Track Finding, main branch (2025.01.09.)
  device/common/include/traccc/finding/device/impl/build_tracks.ipp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
  device/sycl/CMakeLists.txt
  device/sycl/include/traccc/sycl/finding/combinatorial_kalman_filter_algorithm.hpp
  device/sycl/src/finding/combinatorial_kalman_filter_algorithm.cpp
  device/sycl/src/finding/combinatorial_kalman_filter_algorithm_constant_field_default_detector.sycl
  device/sycl/src/finding/combinatorial_kalman_filter_algorithm_constant_field_telescope_detector.sycl
  device/sycl/src/finding/find_tracks.hpp
  extern/dpl/CMakeLists.txt
  tests/sycl/CMakeLists.txt
  tests/sycl/test_ckf_combinatorics_telescope.cpp
  tests/sycl/test_ckf_toy_detector.cpp
  tests/sycl/test_queue.hpp
  tests/sycl/test_queue.sycl
Labels: feature, sycl

#812 SYCL Track Finding in the Example Executables, main branch (2025.01.09.)
  README.md
  device/sycl/CMakeLists.txt
  device/sycl/include/traccc/sycl/clusterization/measurement_sorting_algorithm.hpp
  device/sycl/src/clusterization/measurement_sorting_algorithm.sycl
  examples/run/sycl/full_chain_algorithm.hpp
  examples/run/sycl/full_chain_algorithm.sycl
  examples/run/sycl/seq_example_sycl.sycl
Labels: feature, sycl, examples

#814 Add traccc tuple and pair types
  core/include/traccc/edm/details/container_base.hpp
  core/include/traccc/finding/candidate_link.hpp
  core/include/traccc/utils/pair.hpp
  core/include/traccc/utils/tuple.hpp
Labels: refactor, shared

#819 Remove Thrust pair type from prefix sum code
  device/common/include/traccc/device/fill_prefix_sum.hpp
  device/common/include/traccc/device/impl/fill_prefix_sum.ipp
Labels: refactor, shared

#816 Update NVIDIA CCCL to v2.7.0
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
  extern/cccl/CMakeLists.txt
Labels: build

#823 Fix global counter conversion issue in Kokkos
  device/kokkos/src/seeding/spacepoint_binning.cpp
Labels: bug, kokkos

#821 Fix several SYCL, OneDPL, and Kokkos build issues
  CMakeLists.txt
  device/sycl/src/clusterization/measurement_sorting_algorithm.sycl
  device/sycl/src/finding/find_tracks.hpp
  device/sycl/src/fitting/fit_tracks.hpp
  tests/sycl/test_dpl.sycl
Labels: bug, build, sycl, kokkos

#822 Add structured configuration printing
  examples/CMakeLists.txt
  examples/options/CMakeLists.txt
  examples/options/include/traccc/options/accelerator.hpp
  examples/options/include/traccc/options/clusterization.hpp
  examples/options/include/traccc/options/details/interface.hpp
  examples/options/include/traccc/options/detector.hpp
  examples/options/include/traccc/options/generation.hpp
  examples/options/include/traccc/options/input_data.hpp
  examples/options/include/traccc/options/output_data.hpp
  examples/options/include/traccc/options/performance.hpp
  examples/options/include/traccc/options/telescope_detector.hpp
  examples/options/include/traccc/options/threading.hpp
  examples/options/include/traccc/options/throughput.hpp
  examples/options/include/traccc/options/track_finding.hpp
  examples/options/include/traccc/options/track_propagation.hpp
  examples/options/include/traccc/options/track_resolution.hpp
  examples/options/include/traccc/options/track_seeding.hpp
  examples/options/src/accelerator.cpp
  examples/options/src/clusterization.cpp
  examples/options/src/details/interface.cpp
  examples/options/src/detector.cpp
  examples/options/src/generation.cpp
  examples/options/src/input_data.cpp
  examples/options/src/output_data.cpp
  examples/options/src/performance.cpp
  examples/options/src/program_options.cpp
  examples/options/src/telescope_detector.cpp
  examples/options/src/threading.cpp
  examples/options/src/throughput.cpp
  examples/options/src/track_finding.cpp
  examples/options/src/track_propagation.cpp
  examples/options/src/track_resolution.cpp
  examples/options/src/track_seeding.cpp
  examples/utils/CMakeLists.txt
  examples/utils/include/traccc/examples/utils/printable.hpp
  examples/utils/src/printable.cpp
Labels: improvement

#825 Fix zero-track edge case bug in CUDA track finding
  device/common/include/traccc/finding/device/impl/prune_tracks.ipp
  device/cuda/src/finding/finding_algorithm.cu
Labels: bug, cuda

#826 Remove obsolete Thrust functionality check
  extern/cccl/CMakeLists.txt
Labels: build, cleanup

#828 Fix broken assertion in prune tracks kernel
  device/common/include/traccc/finding/device/impl/prune_tracks.ipp
Labels: bug, shared

#830 Add deterministic processing mode to examples
  examples/options/include/traccc/options/throughput.hpp
  examples/options/src/throughput.cpp
  examples/run/common/throughput_mt.ipp
  examples/run/common/throughput_st.ipp
Labels: feature, examples

#827 Version Update, main branch (2025.01.29.)
  CMakeLists.txt
Labels: build

#829 Make Thrust a private dependency of the CUDA library
  device/cuda/CMakeLists.txt
  device/cuda/include/traccc/cuda/finding/finding_algorithm.hpp
Labels: bug, build
