Repository acts-project/traccc, pull requests merged in 2025-08, with the labels that each got.

#1063 Accelerate spacepoint IO code
  io/src/csv/read_spacepoints.cpp
Labels: performance

#1116 Shrink ODD seeding delta-r cut
  core/include/traccc/seeding/detail/seeding_config.hpp
Labels: performance, physics

#1118 Disable combinatorics in CKF by default
  core/include/traccc/finding/finding_config.hpp
Labels: performance, physics

#1119 Add track purity and completeness to ROOT output
  performance/include/traccc/resolution/stat_plot_tool_config.hpp
  performance/src/efficiency/finding_performance_writer.cpp
  performance/src/resolution/stat_plot_tool.cpp
  performance/src/resolution/stat_plot_tool.hpp
  performance/src/resolution/stat_plot_tool.ipp
Labels: physics

#1120 Reset CKF parameters in toy detector tests
  tests/cuda/test_ckf_toy_detector.cpp
  tests/sycl/test_ckf_toy_detector.cpp
Labels: bug

#1127 Constant Detector, main branch (2025.08.15.)
  benchmarks/cuda/toy_detector_cuda.cpp
  core/include/traccc/geometry/detector.hpp
  device/alpaka/include/traccc/alpaka/seeding/spacepoint_formation_algorithm.hpp
  device/alpaka/src/finding/combinatorial_kalman_filter.hpp
  device/alpaka/src/fitting/kalman_fitting.hpp
  device/alpaka/src/seeding/spacepoint_formation_algorithm.cpp
  device/common/include/traccc/finding/device/apply_interaction.hpp
  device/common/include/traccc/finding/device/find_tracks.hpp
  device/common/include/traccc/finding/device/propagate_to_next_surface.hpp
  device/common/include/traccc/fitting/device/fit.hpp
  device/common/include/traccc/seeding/device/form_spacepoints.hpp
  device/common/include/traccc/seeding/device/impl/form_spacepoints.ipp
  device/cuda/include/traccc/cuda/seeding/spacepoint_formation_algorithm.hpp
  device/cuda/src/finding/combinatorial_kalman_filter.cuh
  device/cuda/src/fitting/kalman_fitting.cuh
  device/cuda/src/seeding/spacepoint_formation_algorithm.cu
  device/sycl/src/finding/combinatorial_kalman_filter.hpp
  device/sycl/src/fitting/kalman_fitting.hpp
  device/sycl/src/seeding/silicon_pixel_spacepoint_formation.hpp
  examples/run/alpaka/full_chain_algorithm.cpp
  examples/run/alpaka/full_chain_algorithm.hpp
  examples/run/alpaka/seeding_example_alpaka.cpp
  examples/run/alpaka/seq_example_alpaka.cpp
  examples/run/cuda/full_chain_algorithm.cpp
  examples/run/cuda/full_chain_algorithm.hpp
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/seq_example_cuda.cpp
  examples/run/cuda/truth_finding_example_cuda.cpp
  examples/run/cuda/truth_fitting_example_cuda.cpp
  examples/run/sycl/full_chain_algorithm.hpp
  examples/run/sycl/full_chain_algorithm.sycl
  examples/run/sycl/seeding_example_sycl.sycl
  examples/run/sycl/seq_example_sycl.sycl
  tests/cuda/test_ckf_combinatorics_telescope.cpp
  tests/cuda/test_ckf_toy_detector.cpp
  tests/cuda/test_kalman_fitter_telescope.cpp
  tests/cuda/test_spacepoint_formation.cpp
  tests/sycl/test_ckf_combinatorics_telescope.cpp
  tests/sycl/test_ckf_toy_detector.cpp
  tests/sycl/test_kalman_fitter_telescope.cpp
  tests/sycl/test_spacepoint_formation.cpp
Labels: improvement

#1128 Fix and rework Kálmán filter p and pT cuts
  core/include/traccc/finding/details/combinatorial_kalman_filter.hpp
  core/include/traccc/finding/finding_config.hpp
  device/common/include/traccc/finding/device/impl/propagate_to_next_surface.ipp
  examples/options/src/track_finding.cpp
  tests/cpu/test_ckf_sparse_tracks_telescope.cpp
Labels: bug, improvement, performance

#1133 Replace deprecated `thrust::identity` type
  device/cuda/src/ambiguity_resolution/greedy_ambiguity_resolution_algorithm.cu
Labels: bug

#1138 Initialize `is_updated` buffer to zero vector correctly
  device/cuda/src/ambiguity_resolution/greedy_ambiguity_resolution_algorithm.cu
Labels: bug

#1142 Optimize the bitonic sort with warp-level primitives
  device/cuda/src/ambiguity_resolution/kernels/remove_tracks.cu
Labels: improvement, AI assistance

#1145 Simplify iterators in Kálmán actor
  core/include/traccc/fitting/kalman_filter/kalman_actor.hpp
  core/include/traccc/fitting/kalman_filter/kalman_fitter.hpp
Labels: refactor
