Repository acts-project/traccc, pull requests merged in 2025-09, with the labels that each got.

#1147 Automatically generate kernel specializations
  CMakeLists.txt
  codegen/kernel_specialization/gen_kernel_specialization.py
  device/cuda/CMakeLists.txt
  device/cuda/src/finding/kernels/specializations/apply_interaction.cu.template
  device/cuda/src/finding/kernels/specializations/apply_interaction_telescope_detector.cu
  device/cuda/src/finding/kernels/specializations/find_tracks.cu.template
  device/cuda/src/finding/kernels/specializations/find_tracks_telescope_detector.cu
  device/cuda/src/finding/kernels/specializations/propagate_to_next_surface.cu.template
  device/cuda/src/finding/kernels/specializations/propagate_to_next_surface_constant_field_default_detector.cu
  device/cuda/src/finding/kernels/specializations/propagate_to_next_surface_inhomogeneous_global_field_default_detector.cu
  device/cuda/src/finding/kernels/specializations/propagate_to_next_surface_inhomogeneous_global_field_telescope_detector.cu
  device/cuda/src/finding/kernels/specializations/propagate_to_next_surface_inhomogeneous_texture_field_default_detector.cu
  device/cuda/src/finding/kernels/specializations/propagate_to_next_surface_inhomogeneous_texture_field_telescope_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_backward.cu.template
  device/cuda/src/fitting/kernels/specializations/fit_backward_constant_field_default_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_backward_constant_field_telescope_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_backward_inhomogeneous_global_field_default_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_backward_inhomogeneous_global_field_telescope_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_backward_inhomogeneous_texture_field_telescope_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_forward.cu.template
  device/cuda/src/fitting/kernels/specializations/fit_forward_constant_field_default_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_forward_constant_field_telescope_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_forward_inhomogeneous_global_field_default_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_forward_inhomogeneous_global_field_telescope_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_forward_inhomogeneous_texture_field_telescope_detector.cu
Labels: build

#1151 Bug Fix: Correct copy typo.
  examples/run/alpaka/seq_example_alpaka.cpp
Labels: bug

#1146 Avoid async size copies into pageable memory
  device/cuda/src/clusterization/measurement_sorting_algorithm.cu
  device/cuda/src/finding/combinatorial_kalman_filter.cuh
  device/cuda/src/seeding/seed_finding.cu
  device/cuda/src/seeding/spacepoint_binning.cu
  device/cuda/src/seeding/spacepoint_formation_algorithm.cu
  device/cuda/src/seeding/track_params_estimation.cu
  device/cuda/src/utils/get_size.hpp
  tests/cuda/test_spacepoint_formation.cpp
Labels: performance

#1153 Fix hole and tip making bugs in track finding
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
Labels: bug

#949 ref: Use track parameter vector directly in seeding
  core/include/traccc/edm/track_parameters.hpp
  core/include/traccc/seeding/detail/spacepoint_formation.hpp
  core/include/traccc/seeding/impl/spacepoint_formation.ipp
  core/include/traccc/seeding/track_params_estimation_helper.hpp
  core/src/seeding/track_params_estimation.cpp
  device/common/include/traccc/seeding/device/impl/estimate_track_params.ipp
Labels: cleanup

#1159 Free the memory properly in `array-wrapper-test`
  tests/cuda/test_array_wrapper.cu
Labels: bug
