Repository acts-project/traccc, pull requests merged in 2025-02, with the labels that each got.

#831 Add code for per-commit benchmarking
  extras/commit_benchmark/.gitignore
  extras/commit_benchmark/benchmark.py
  extras/commit_benchmark/plot.py
  extras/commit_benchmark/poetry.lock
  extras/commit_benchmark/pyproject.toml
Labels: feature, extras

#833 Use configuration types as SSOT for defaults
  examples/options/include/traccc/options/clusterization.hpp
  examples/options/include/traccc/options/track_finding.hpp
  examples/options/include/traccc/options/track_propagation.hpp
  examples/options/src/clusterization.cpp
  examples/options/src/track_finding.cpp
  examples/options/src/track_propagation.cpp
Labels: improvement, examples

#835 Use caching allocators in Thrust
  device/cuda/include/traccc/cuda/clusterization/measurement_sorting_algorithm.hpp
  device/cuda/src/clusterization/measurement_sorting_algorithm.cu
  device/cuda/src/finding/finding_algorithm.cu
  device/cuda/src/fitting/fitting_algorithm.cu
  examples/run/cuda/full_chain_algorithm.cpp
  examples/run/cuda/seq_example_cuda.cpp
Labels: cuda, improvement, performance

#836 Increase collection comparison performance
  performance/CMakeLists.txt
  performance/include/traccc/performance/details/comparison_progress.hpp
  performance/include/traccc/performance/details/projector.hpp
  performance/include/traccc/performance/impl/collection_comparator.ipp
  performance/src/performance/details/comparison_progress.cpp
Labels: improvement, performance, physics, examples

#839 Fix missing typename in sanity checks
  core/include/traccc/sanity/contiguous_on.hpp
Labels: bug

#843 Asynchronous Thrust, main branch (2025.02.05.)
  device/cuda/src/clusterization/measurement_sorting_algorithm.cu
  device/cuda/src/finding/finding_algorithm.cu
  device/cuda/src/fitting/fitting_algorithm.cu
Labels: performance

#845 Configuration Updates, main branch (2025.02.07.)
  core/include/traccc/fitting/fitting_config.hpp
  examples/options/CMakeLists.txt
  examples/options/include/traccc/options/details/interface.hpp
  examples/options/include/traccc/options/detector.hpp
  examples/options/include/traccc/options/input_data.hpp
  examples/options/include/traccc/options/track_fitting.hpp
  examples/options/src/accelerator.cpp
  examples/options/src/clusterization.cpp
  examples/options/src/detector.cpp
  examples/options/src/generation.cpp
  examples/options/src/input_data.cpp
  examples/options/src/output_data.cpp
  examples/options/src/performance.cpp
  examples/options/src/telescope_detector.cpp
  examples/options/src/threading.cpp
  examples/options/src/throughput.cpp
  examples/options/src/track_finding.cpp
  examples/options/src/track_fitting.cpp
  examples/options/src/track_propagation.cpp
  examples/options/src/track_resolution.cpp
  examples/options/src/track_seeding.cpp
  examples/run/alpaka/seeding_example_alpaka.cpp
  examples/run/common/throughput_mt.ipp
  examples/run/common/throughput_st.ipp
  examples/run/cpu/seeding_example.cpp
  examples/run/cpu/seq_example.cpp
  examples/run/cpu/truth_finding_example.cpp
  examples/run/cpu/truth_fitting_example.cpp
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/seq_example_cuda.cpp
  examples/run/cuda/truth_finding_example_cuda.cpp
  examples/run/cuda/truth_fitting_example_cuda.cpp
  examples/run/kokkos/seeding_example_kokkos.cpp
  examples/run/sycl/seq_example_sycl.sycl
Labels: examples

#848 Seed Parameter Estimation Fix, main branch (2025.02.10.)
  core/include/traccc/seeding/track_params_estimation_helper.hpp
Labels: bug

#850 Git Ignore Update, main branch (2025.02.10.)
  .gitignore
Labels: build

#863 Fix the bug in getting the first smoother state
  core/include/traccc/fitting/kalman_filter/kalman_fitter.hpp
Labels: bug

#868 Divide default propagation options by proper units
  examples/options/src/track_propagation.cpp
Labels: bug

#861 Return error state if PDG number is unknown
  core/include/traccc/utils/particle.hpp
Labels: bug, edm

#866 ref: Use traccc unit and constant definitions everywhere
  benchmarks/common/benchmarks/toy_detector_benchmark.hpp
  core/include/traccc/finding/finding_config.hpp
  core/include/traccc/fitting/fitting_config.hpp
  core/include/traccc/seeding/track_params_estimation.hpp
  device/alpaka/include/traccc/alpaka/seeding/track_params_estimation.hpp
  device/cuda/include/traccc/cuda/seeding/track_params_estimation.hpp
  device/sycl/include/traccc/sycl/seeding/track_params_estimation.hpp
  examples/options/include/traccc/options/track_finding.hpp
  examples/options/src/generation.cpp
  examples/options/src/telescope_detector.cpp
  examples/options/src/track_propagation.cpp
  examples/run/cpu/seeding_example.cpp
  examples/run/cpu/truth_finding_example.cpp
  examples/run/cpu/truth_fitting_example.cpp
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/truth_finding_example_cuda.cpp
  examples/run/cuda/truth_fitting_example_cuda.cpp
  examples/simulation/simulate.cpp
  examples/simulation/simulate_telescope.cpp
  examples/simulation/simulate_toy_detector.cpp
  examples/simulation/simulate_wire_chamber.cpp
  tests/common/tests/kalman_fitting_momentum_resolution_test.hpp
  tests/common/tests/kalman_fitting_telescope_test.hpp
  tests/common/tests/kalman_fitting_toy_detector_test.hpp
  tests/common/tests/kalman_fitting_wire_chamber_test.hpp
  tests/cpu/test_ckf_combinatorics_telescope.cpp
  tests/cpu/test_ckf_sparse_tracks_telescope.cpp
  tests/cpu/test_kalman_fitter_hole_count.cpp
  tests/cpu/test_kalman_fitter_momentum_resolution.cpp
  tests/cpu/test_kalman_fitter_telescope.cpp
  tests/cpu/test_kalman_fitter_wire_chamber.cpp
  tests/cpu/test_ranges.cpp
  tests/cpu/test_simulation.cpp
  tests/cpu/test_spacepoint_formation.cpp
  tests/cuda/test_ckf_combinatorics_telescope.cpp
  tests/cuda/test_ckf_toy_detector.cpp
  tests/cuda/test_kalman_fitter_telescope.cpp
  tests/cuda/test_spacepoint_formation.cpp
  tests/sycl/test_ckf_combinatorics_telescope.cpp
  tests/sycl/test_ckf_toy_detector.cpp
  tests/sycl/test_spacepoint_formation.sycl
Labels: cleanup

#859 Minor fixes to the track building kernel
  core/include/traccc/finding/details/find_tracks.hpp
  device/common/include/traccc/finding/device/impl/build_tracks.ipp
Labels: bug, shared

#871 Add pre-commit job to check quote includes
  .github/check_quote_includes.sh
  .pre-commit-config.yaml
  device/common/include/traccc/clusterization/device/impl/ccl_kernel.ipp
  device/cuda/include/traccc/cuda/utils/make_prefix_sum_buff.hpp
  device/cuda/src/seeding/seed_finding.cu
  device/futhark/include/traccc/futhark/component_connection.hpp
  device/sycl/include/traccc/sycl/utils/make_prefix_sum_buff.hpp
  tests/common/tests/atlas_cuts.hpp
  tests/cpu/compare_with_acts_seeding.cpp
  tests/cpu/test_cca.cpp
Labels: cicd

#841 ref: update detray to v0.88.1
  benchmarks/common/benchmarks/toy_detector_benchmark.hpp
  core/include/traccc/definitions/primitives.hpp
  core/include/traccc/finding/details/find_tracks.hpp
  core/include/traccc/fitting/details/fit_tracks.hpp
  core/include/traccc/fitting/kalman_filter/kalman_actor.hpp
  core/include/traccc/fitting/kalman_filter/kalman_fitter.hpp
  core/include/traccc/seeding/detail/spacepoint_grid.hpp
  core/include/traccc/utils/seed_generator.hpp
  core/src/seeding/spacepoint_binning.cpp
  device/cuda/include/traccc/cuda/finding/finding_algorithm.hpp
  device/cuda/src/finding/kernels/specializations/types.hpp
  device/sycl/src/finding/find_tracks.hpp
  examples/simulation/simulate_telescope.cpp
  extern/detray/CMakeLists.txt
  plugins/algebra/array/include/traccc/plugins/algebra/array_definitions.hpp
  simulation/include/traccc/simulation/measurement_smearer.hpp
  simulation/include/traccc/simulation/simulator.hpp
  tests/common/tests/kalman_fitting_momentum_resolution_test.hpp
  tests/common/tests/kalman_fitting_telescope_test.hpp
  tests/cpu/test_spacepoint_formation.cpp
  tests/cpu/test_track_params_estimation.cpp
  tests/cuda/test_spacepoint_formation.cpp
  tests/sycl/test_spacepoint_formation.sycl
Labels: bug, feature

#862 Add failure propagation to Kálmán filter code
  core/include/traccc/finding/details/find_tracks.hpp
  core/include/traccc/fitting/details/fit_tracks.hpp
  core/include/traccc/fitting/kalman_filter/gain_matrix_smoother.hpp
  core/include/traccc/fitting/kalman_filter/gain_matrix_updater.hpp
  core/include/traccc/fitting/kalman_filter/kalman_actor.hpp
  core/include/traccc/fitting/kalman_filter/kalman_fitter.hpp
  core/include/traccc/fitting/kalman_filter/two_filters_smoother.hpp
  core/include/traccc/fitting/status_codes.hpp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
  device/common/include/traccc/fitting/device/impl/fit.ipp
  tests/cpu/test_kalman_fitter_wire_chamber.cpp
Labels: improvement, shared

#872 ref: Measure wall time in multithreaded benchmark and reduce number of events
  benchmarks/common/benchmarks/toy_detector_benchmark.hpp
  benchmarks/cpu/toy_detector_cpu.cpp
  benchmarks/cuda/toy_detector_cuda.cpp
Labels: bug

#875 fix: Provide global default for the custom scalar type
  CMakeLists.txt
  plugins/algebra/CMakeLists.txt
Labels: bug

#877 Add B-field conversion and generation tools
  examples/CMakeLists.txt
  examples/tools/CMakeLists.txt
  examples/tools/bfield_type.hpp
  examples/tools/convert_csv_bfield.cpp
  examples/tools/generate_constant_bfield.cpp
Labels: feature, examples

#876 ref: Remove detray unit types
  examples/options/src/track_propagation.cpp
Labels: cleanup

#867 ref: Harmonize track parameters types
  benchmarks/common/benchmarks/toy_detector_benchmark.hpp
  core/include/traccc/edm/track_candidate.hpp
  core/include/traccc/edm/track_parameters.hpp
  core/include/traccc/edm/track_state.hpp
  core/include/traccc/finding/details/find_tracks.hpp
  core/include/traccc/fitting/kalman_filter/gain_matrix_smoother.hpp
  core/include/traccc/fitting/kalman_filter/gain_matrix_updater.hpp
  core/include/traccc/fitting/kalman_filter/two_filters_smoother.hpp
  core/include/traccc/seeding/track_params_estimation_helper.hpp
  core/include/traccc/utils/particle.hpp
  core/include/traccc/utils/seed_generator.hpp
  core/src/seeding/track_params_estimation.cpp
  device/common/include/traccc/edm/device/sort_key.hpp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
  device/common/include/traccc/finding/device/impl/propagate_to_next_surface.ipp
  device/common/include/traccc/seeding/device/impl/estimate_track_params.ipp
  examples/run/alpaka/seeding_example_alpaka.cpp
  examples/run/alpaka/seq_example_alpaka.cpp
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/seq_example_cuda.cpp
  examples/run/sycl/seeding_example_sycl.sycl
  examples/run/sycl/seq_example_sycl.sycl
  examples/simulation/simulate.cpp
  examples/simulation/simulate_telescope.cpp
  examples/simulation/simulate_toy_detector.cpp
  examples/simulation/simulate_wire_chamber.cpp
  performance/include/traccc/performance/details/projector.hpp
  performance/include/traccc/performance/impl/is_same_track_parameters.ipp
  performance/include/traccc/resolution/fitting_performance_writer.hpp
  performance/src/performance/details/is_same_object.cpp
  performance/src/resolution/fitting_performance_writer.cpp
  performance/src/resolution/res_plot_tool.cpp
  performance/src/resolution/res_plot_tool.hpp
  performance/src/utils/event_data.cpp
  simulation/include/traccc/simulation/measurement_smearer.hpp
  simulation/include/traccc/simulation/smearing_writer.hpp
  tests/core/particle.cpp
  tests/cpu/test_ckf_combinatorics_telescope.cpp
  tests/cpu/test_ckf_sparse_tracks_telescope.cpp
  tests/cpu/test_kalman_fitter_hole_count.cpp
  tests/cpu/test_kalman_fitter_momentum_resolution.cpp
  tests/cpu/test_kalman_fitter_telescope.cpp
  tests/cpu/test_kalman_fitter_wire_chamber.cpp
  tests/cpu/test_simulation.cpp
  tests/cuda/test_ckf_combinatorics_telescope.cpp
  tests/cuda/test_ckf_toy_detector.cpp
  tests/cuda/test_kalman_fitter_telescope.cpp
  tests/sycl/test_ckf_combinatorics_telescope.cpp
  tests/sycl/test_ckf_toy_detector.cpp
  tests/sycl/test_kalman_fitter_telescope.sycl
Labels: cleanup

#887 VecMem 1.14.0, main branch (2025.02.21.)
  extern/vecmem/CMakeLists.txt
  io/src/csv/read_cells.cpp
  tests/cpu/seq_single_module.cpp
Labels: edm

#884 Fix edge case detection in CPU track finding
  core/include/traccc/finding/details/find_tracks.hpp
Labels: bug, cpu

#885 Set particle hypothesis in Kálmán fitter
  core/include/traccc/fitting/kalman_filter/kalman_fitter.hpp
Labels: bug

#883 Add pre-commit hook to check for detray units
  .github/check_taboos.sh
  .pre-commit-config.yaml
Labels: cicd

#894 Remove some unused executables
  examples/run/CMakeLists.txt
  examples/run/cpu/CMakeLists.txt
  examples/run/cpu/ccl_example.cpp
  examples/run/cpu/tbb_task_example.cpp
  examples/run/openmp/CMakeLists.txt
  examples/run/openmp/par_example.cpp
Labels: cleanup

#890 Fix SFINAE bug in container base type
  core/include/traccc/edm/details/container_base.hpp
Labels: bug, edm

#898 Logging Tweaks, main branch (2025.02.27.)
  core/CMakeLists.txt
  core/include/traccc/utils/logging.hpp
  core/src/utils/logging.cpp
  examples/options/src/program_options.cpp
  examples/utils/include/traccc/examples/utils/printable.hpp
  examples/utils/src/printable.cpp
Labels: improvement, examples

#895 Protect against negative chi-square in updater
  core/include/traccc/fitting/kalman_filter/gain_matrix_smoother.hpp
  core/include/traccc/fitting/kalman_filter/gain_matrix_updater.hpp
  core/include/traccc/fitting/kalman_filter/two_filters_smoother.hpp
  core/include/traccc/fitting/status_codes.hpp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
  tests/cpu/test_kalman_fitter_momentum_resolution.cpp
Labels: bug
