Repository acts-project/traccc, pull requests merged in 2025-04, with the labels that each got.

#938 Migrate fitting kernels to use a payload struct
  device/alpaka/src/fitting/fitting_algorithm.cpp
  device/common/include/traccc/fitting/device/fit.hpp
  device/common/include/traccc/fitting/device/impl/fit.ipp
  device/cuda/src/fitting/fitting_algorithm.cu
  device/sycl/src/fitting/fit_tracks.hpp
Labels: refactor, cuda, sycl, alpaka, shared

#939 Remove cluster link in measurement edm
  core/include/traccc/edm/measurement.hpp
Labels: performance

#946 fix: IO sorting
  io/include/traccc/io/read_measurements.hpp
  io/src/csv/read_measurements.cpp
  io/src/csv/read_measurements.hpp
  io/src/csv/read_particles.cpp
  io/src/csv/read_particles.hpp
  io/src/csv/read_spacepoints.cpp
  io/src/csv/read_spacepoints.hpp
  io/src/read_measurements.cpp
Labels: bug

#919 Add compatibility with CUDA 12.8
  README.md
  cmake/traccc-compiler-options-cuda.cmake
  device/cuda/CMakeLists.txt
  device/cuda/src/finding/finding_algorithm.cu
  device/cuda/src/finding/kernels/apply_interaction.cuh
  device/cuda/src/finding/kernels/apply_interaction.hpp
  device/cuda/src/finding/kernels/find_tracks.cuh
  device/cuda/src/finding/kernels/propagate_to_next_surface.hpp
  device/cuda/src/finding/kernels/specializations/apply_interaction_default_detector.cu
  device/cuda/src/finding/kernels/specializations/apply_interaction_src.cuh
  device/cuda/src/finding/kernels/specializations/find_tracks_default_detector.cu
  device/cuda/src/finding/kernels/specializations/find_tracks_src.cuh
  device/cuda/src/finding/kernels/specializations/propagate_to_next_surface_default_detector.cu
  device/cuda/src/finding/kernels/specializations/propagate_to_next_surface_src.cuh
  device/cuda/src/finding/kernels/specializations/types.hpp
Labels: build, cuda

#953 SonarCloud VSCode Setup, main branch (2025.04.29.)
  .vscode/settings.json
Labels: build

#954 (Further) CUDA Fixes, main branch (2025.04.29.)
  CMakeLists.txt
  cmake/traccc-compiler-options-cuda.cmake
  device/cuda/src/finding/finding_algorithm.cu
  examples/run/cuda/full_chain_algorithm.cpp
Labels: improvement

#955 Acts v39.0.0, main branch (2025.04.30.)
  extern/acts/CMakeLists.txt
  spack.yaml
Labels: build
