Repository acts-project/traccc, pull requests merged in 2025-03, with the labels that each got.

#900 Improve assertions in Kálmán filter and fitter
  device/common/include/traccc/finding/device/impl/build_tracks.ipp
  device/common/include/traccc/fitting/device/impl/fit.ipp
Labels: improvement, shared

#904 Remove inconsistent CKF options
  examples/options/src/track_finding.cpp
Labels: bug

#903 Add pre-commit checks for whitespace
  .github/wip.yml
  .github/workflows/benchmarks.yml
  .pre-commit-config.yaml
  benchmarks/cpu/CMakeLists.txt
  benchmarks/cpu/toy_detector_cpu.cpp
  benchmarks/cuda/CMakeLists.txt
  core/include/traccc/edm/impl/silicon_cell_collection.ipp
  core/include/traccc/edm/track_candidate.hpp
  core/include/traccc/edm/track_quality.hpp
  core/include/traccc/geometry/geometry.hpp
  core/include/traccc/seeding/impl/spacepoint_formation.ipp
  core/include/traccc/utils/memory_resource.hpp
  core/include/traccc/utils/particle.hpp
  device/kokkos/include/traccc/kokkos/utils/definitions.hpp
  examples/io/CMakeLists.txt
  examples/simulation/CMakeLists.txt
  extern/detray/CMakeLists.txt
  extern/dpl/README.txt
  io/include/traccc/io/csv/make_measurement_edm.hpp
  performance/include/traccc/performance/details/is_same_object.hpp
  performance/src/resolution/res_plot_tool.hpp
  performance/src/utils/event_data.cpp
  tests/common/tests/ckf_toy_detector_test.hpp
  tests/common/tests/kalman_fitting_momentum_resolution_test.cpp
  tests/core/CMakeLists.txt
  tests/core/particle.cpp
  tests/cpu/CMakeLists.txt
  tests/cpu/test_copy.cpp
  tests/cpu/test_kalman_fitter_telescope.cpp
  tests/cuda/test_copy.cu
  tests/hip/CMakeLists.txt
  tests/sycl/test_dpl.sycl
Labels: cicd, formatting

#911 Fix: uninitialized value when the first step is skipped
  device/common/include/traccc/finding/device/impl/build_tracks.ipp
Labels: bug

#910 Sort truth track measurements by time
  core/include/traccc/edm/measurement.hpp
  io/src/csv/make_measurement_edm.cpp
  performance/src/utils/event_data.cpp
Labels: bug, examples

#916 Fix bug in seed selection in track finder
  core/include/traccc/finding/details/find_tracks.hpp
  device/common/include/traccc/finding/device/impl/build_tracks.ipp
Labels: bug, cpu, shared

#921 Make CKF types and initializers more readable
  core/include/traccc/finding/candidate_link.hpp
  core/include/traccc/finding/candidate_tip.hpp
  core/include/traccc/finding/details/find_tracks.hpp
  device/common/include/traccc/finding/device/build_tracks.hpp
  device/common/include/traccc/finding/device/find_tracks.hpp
  device/common/include/traccc/finding/device/impl/build_tracks.ipp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
  device/common/include/traccc/finding/device/impl/propagate_to_next_surface.ipp
  device/common/include/traccc/finding/device/propagate_to_next_surface.hpp
  device/cuda/src/finding/finding_algorithm.cu
  device/sycl/src/finding/find_tracks.hpp
Labels: refactor, shared

#920 Fix `TRACCC_USE_SPACK_LIBS` CMake variable
  CMakeLists.txt
Labels: bug, build

#927 Accelerate and update commit benchmarking script
  extras/commit_benchmark/benchmark.py
  extras/commit_benchmark/plot.py
Labels: extras

#924 Allocate CKF links in a flat allocation
  core/include/traccc/finding/candidate_link.hpp
  core/include/traccc/finding/candidate_tip.hpp
  core/include/traccc/finding/details/find_tracks.hpp
  core/include/traccc/finding/finding_config.hpp
  device/common/include/traccc/finding/device/build_tracks.hpp
  device/common/include/traccc/finding/device/find_tracks.hpp
  device/common/include/traccc/finding/device/impl/build_tracks.ipp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
  device/common/include/traccc/finding/device/impl/propagate_to_next_surface.ipp
  device/common/include/traccc/finding/device/propagate_to_next_surface.hpp
  device/cuda/src/finding/finding_algorithm.cu
  device/sycl/src/finding/find_tracks.hpp
Labels: improvement, shared

#928 Update detray external to v0.94.0
  extern/detray/CMakeLists.txt
  tests/common/tests/kalman_fitting_momentum_resolution_test.cpp
  tests/cpu/test_track_params_estimation.cpp
Labels: performance

#860 Allow event data reader to work on Geant4 data
  examples/options/CMakeLists.txt
  examples/options/include/traccc/options/truth_finding.hpp
  examples/options/src/truth_finding.cpp
  examples/run/cpu/truth_finding_example.cpp
  examples/run/cuda/truth_finding_example_cuda.cpp
  performance/include/traccc/utils/event_data.hpp
  performance/src/utils/event_data.cpp
Labels: improvement, physics, examples
