Repository acts-project/traccc, pull requests merged in 2025-07, with the labels that each got.

#1049 Add clamping to magnetic field types
  core/include/traccc/utils/bfield.hpp
  device/cuda/src/utils/bfield.cuh
  device/sycl/src/utils/bfield.hpp
  extern/covfie/CMakeLists.txt
  io/src/read_bfield.cpp
Labels: improvement

#1038 Switch from synchronized propagator to default
  core/include/traccc/finding/details/combinatorial_kalman_filter.hpp
  device/common/include/traccc/finding/device/impl/propagate_to_next_surface.ipp
Labels: performance

#1043 Add additional information to candidate links
  core/include/traccc/finding/candidate_link.hpp
  core/include/traccc/finding/details/combinatorial_kalman_filter.hpp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
Labels: improvement, shared

#1039 Update algebra plugins to v0.28.0
  core/include/traccc/fitting/kalman_filter/gain_matrix_updater.hpp
  core/include/traccc/fitting/kalman_filter/two_filters_smoother.hpp
  extern/algebra-plugins/CMakeLists.txt
Labels: build, performance

#1051 Inhomogeneous Magnetic Field Throughput Applications, main branch (2025.07.02.)
  examples/run/alpaka/CMakeLists.txt
  examples/run/alpaka/full_chain_algorithm.cpp
  examples/run/alpaka/full_chain_algorithm.hpp
  examples/run/common/throughput_mt.ipp
  examples/run/common/throughput_st.ipp
  examples/run/cpu/full_chain_algorithm.cpp
  examples/run/cpu/full_chain_algorithm.hpp
  examples/run/cuda/full_chain_algorithm.cpp
  examples/run/cuda/full_chain_algorithm.hpp
  examples/run/sycl/full_chain_algorithm.hpp
  examples/run/sycl/full_chain_algorithm.sycl
Labels: feature, examples

#1059 Update covfie to v0.15.2
  extern/covfie/CMakeLists.txt
Labels: build

#1062 Update detray to v0.101.0
  extern/detray/CMakeLists.txt
Labels: build

#1070 Make `find_valid_index` not repeat the same index in the iteration
  device/cuda/src/ambiguity_resolution/kernels/rearrange_tracks.cu
Labels: bug

#1066 Honour subspaces in measurement creation
  core/include/traccc/clusterization/impl/measurement_creation.ipp
  core/include/traccc/geometry/silicon_detector_description.hpp
  device/common/include/traccc/clusterization/device/impl/aggregate_cluster.ipp
  io/src/read_detector_description.cpp
Labels: feature

#1078 CKF Track Deduplication, main branch (2025.07.15.)
  device/alpaka/src/finding/combinatorial_kalman_filter.hpp
  device/common/include/traccc/finding/device/remove_duplicates.hpp
  device/sycl/src/finding/combinatorial_kalman_filter.hpp
  tests/sycl/test_ckf_toy_detector.cpp
Labels: bug, sycl, alpaka, high priority

#1071 CUDA Texture B-Field, main branch (2025.07.11.)
  device/cuda/CMakeLists.txt
  device/cuda/include/traccc/cuda/utils/make_magnetic_field.hpp
  device/cuda/src/finding/combinatorial_kalman_filter_algorithm_default_detector.cu
  device/cuda/src/finding/combinatorial_kalman_filter_algorithm_telescope_detector.cu
  device/cuda/src/finding/kernels/specializations/propagate_to_next_surface_inhomogeneous_global_field_default_detector.cu
  device/cuda/src/finding/kernels/specializations/propagate_to_next_surface_inhomogeneous_global_field_telescope_detector.cu
  device/cuda/src/finding/kernels/specializations/propagate_to_next_surface_inhomogeneous_texture_field_default_detector.cu
  device/cuda/src/finding/kernels/specializations/propagate_to_next_surface_inhomogeneous_texture_field_telescope_detector.cu
  device/cuda/src/fitting/kalman_fitting_algorithm_default_detector.cu
  device/cuda/src/fitting/kalman_fitting_algorithm_telescope_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_backward_inhomogeneous_global_field_default_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_backward_inhomogeneous_global_field_telescope_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_backward_inhomogeneous_texture_field_default_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_backward_inhomogeneous_texture_field_telescope_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_forward_inhomogeneous_global_field_default_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_forward_inhomogeneous_global_field_telescope_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_forward_inhomogeneous_texture_field_default_detector.cu
  device/cuda/src/fitting/kernels/specializations/fit_forward_inhomogeneous_texture_field_telescope_detector.cu
  device/cuda/src/utils/magnetic_field_types.hpp
  device/cuda/src/utils/make_magnetic_field.cpp
  examples/options/include/traccc/options/accelerator.hpp
  examples/options/src/accelerator.cpp
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/seq_example_cuda.cpp
Labels: feature, cuda

#1077 Add truth finding cuts and efficiency output
  examples/options/include/traccc/options/truth_finding.hpp
  examples/options/src/truth_finding.cpp
  examples/run/alpaka/seeding_example_alpaka.cpp
  examples/run/cpu/seeding_example.cpp
  examples/run/cpu/seq_example.cpp
  examples/run/cpu/truth_finding_example.cpp
  examples/run/cuda/seeding_example_cuda.cpp
  examples/run/cuda/truth_finding_example_cuda.cpp
  performance/include/traccc/efficiency/finding_performance_writer.hpp
  performance/include/traccc/utils/truth_matching_config.hpp
  performance/src/efficiency/finding_performance_writer.cpp
Labels: feature, examples

#1092 Move insertion mutex code to dedicated header
  device/common/include/traccc/device/array_insertion_mutex.hpp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
Labels: refactor

#1045 Add pre-commit check for duplicate CUDA files
  .github/check_duplicate_cu_files.sh
  .pre-commit-config.yaml
Labels: cicd

#1097 Embed bottom and middle spacepoint in triplet
  core/include/traccc/seeding/seed_selecting_helper.hpp
  core/src/seeding/seed_filtering.cpp
  device/alpaka/src/seeding/seed_finding.cpp
  device/common/include/traccc/edm/device/device_triplet.hpp
  device/common/include/traccc/seeding/device/impl/find_triplets.ipp
  device/common/include/traccc/seeding/device/impl/select_seeds.ipp
  device/common/include/traccc/seeding/device/impl/update_triplet_weights.ipp
  device/common/include/traccc/seeding/device/update_triplet_weights.hpp
  device/cuda/src/seeding/seed_finding.cu
  device/sycl/src/seeding/seed_finding.sycl
Labels: refactor
