Repository acts-project/traccc, pull requests merged in 2025-05, with the labels that each got.

#962 VecMem 1.16.0 Update, main branch (2025.05.05.)
  examples/run/common/throughput_mt.ipp
  examples/run/common/throughput_st.ipp
  extern/vecmem/CMakeLists.txt
Labels: build

#956 Accelerate and fix bug in performance code
  performance/include/traccc/resolution/fitting_performance_writer.hpp
  performance/src/resolution/res_plot_tool.cpp
  performance/src/utils/event_data.cpp
Labels: bug, performance, physics

#964 Simplified Seed Selection, main branch (2025.05.05.)
  device/common/include/traccc/seeding/device/impl/select_seeds.ipp
Labels: improvement, edm

#972 CUDA VSCode Debugging, main branch (2025.05.11.)
  .vscode/launch.json
Labels: build

#957 SYCL Fixes, main branch (2025.04.30.)
  core/include/traccc/utils/prob.hpp
  device/sycl/src/sanity/contiguous_on.hpp
Labels: sycl, cpu

#970 Clean Device Track Finding, main branch (2025.05.08.)
  device/alpaka/include/traccc/alpaka/finding/finding_algorithm.hpp
  device/alpaka/src/finding/finding_algorithm.cpp
  device/cuda/include/traccc/cuda/finding/finding_algorithm.hpp
  device/cuda/src/finding/finding_algorithm.cu
Labels: cuda, alpaka

#965 Strip Spacepoints, main branch (2025.05.05.)
  core/include/traccc/edm/impl/spacepoint_collection.ipp
  core/include/traccc/edm/spacepoint_collection.hpp
  core/include/traccc/seeding/track_params_estimation_helper.hpp
  core/src/seeding/silicon_pixel_spacepoint_formation.hpp
  core/src/seeding/track_params_estimation.cpp
  device/common/include/traccc/seeding/device/impl/estimate_track_params.ipp
  device/common/include/traccc/seeding/device/impl/form_spacepoints.ipp
  io/src/csv/read_spacepoints.cpp
  performance/include/traccc/efficiency/nseed_performance_writer.hpp
  performance/src/efficiency/seeding_performance_writer.cpp
  tests/cpu/test_seeding.cpp
  tests/cpu/test_track_params_estimation.cpp
Labels: feature, edm

#978 VecMem 1.17.0 Update, main branch (2025.05.15.)
  extern/vecmem/CMakeLists.txt
  tests/sycl/CMakeLists.txt
  tests/sycl/test_ckf_combinatorics_telescope.cpp
  tests/sycl/test_ckf_toy_detector.cpp
  tests/sycl/test_kalman_fitter_telescope.cpp
  tests/sycl/test_queue.hpp
  tests/sycl/test_queue.sycl
Labels: build, tests, sycl

#974 CMake 4 Updates, main branch (2025.05.13.)
  extern/alpaka/CMakeLists.txt
  extern/alpaka/alpaka-1.2.0-cmake-boost.patch
  extern/alpaka/alpaka-1.2.0-sycl-amd.patch
  extern/dfelibs/CMakeLists.txt
  extern/eigen3/CMakeLists.txt
  extern/indicators/CMakeLists.txt
  extern/tbb/CMakeLists.txt
Labels: build

#982 Add translation to silicon detector description
  core/include/traccc/geometry/silicon_detector_description.hpp
  device/common/include/traccc/clusterization/device/impl/aggregate_cluster.ipp
  io/src/read_detector_description.cpp
  tests/common/tests/cca_test.hpp
Labels: feature, edm, shared

#908 Improve memory usage in track finding postamble
  device/alpaka/src/finding/finding_algorithm.cpp
  device/common/include/traccc/finding/device/find_tracks.hpp
  device/common/include/traccc/finding/device/impl/build_tracks.ipp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
  device/common/include/traccc/finding/device/impl/propagate_to_next_surface.ipp
  device/common/include/traccc/finding/device/propagate_to_next_surface.hpp
  device/cuda/src/finding/finding_algorithm.cu
  device/sycl/src/finding/find_tracks.hpp
Labels: cuda, improvement, sycl, shared

#929 Keep states ordered by quality in CKF
  device/alpaka/src/finding/finding_algorithm.cpp
  device/alpaka/src/finding/kernels/find_tracks.hpp
  device/common/include/traccc/finding/device/find_tracks.hpp
  device/common/include/traccc/finding/device/impl/find_tracks.ipp
  device/cuda/src/finding/finding_algorithm.cu
  device/cuda/src/finding/kernels/specializations/find_tracks_src.cuh
  device/sycl/src/finding/find_tracks.hpp
Labels: improvement, shared

#990 Increment version number to v0.22.0
  CMakeLists.txt
Labels: build

#996 VecMem 1.18.0 Update, main branch (2025.05.30.)
  device/common/include/traccc/device/impl/container_d2h_copy_alg.ipp
  device/common/include/traccc/device/impl/container_h2d_copy_alg.ipp
  extern/vecmem/CMakeLists.txt
Labels: build, improvement
